// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wire/v1/control.proto

package wirev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResultCode int32

const (
	ResultCode_RESULT_CODE_UNSPECIFIED              ResultCode = 0
	ResultCode_RESULT_CODE_ACCEPTED                 ResultCode = 1
	ResultCode_RESULT_CODE_INCOMPATIBLE_VERSION     ResultCode = 2
	ResultCode_RESULT_CODE_MISSING_REQUIRED_FEATURE ResultCode = 3
	ResultCode_RESULT_CODE_INVALID_PARAMETER        ResultCode = 4
	ResultCode_RESULT_CODE_SESSION_COLLISION        ResultCode = 5
)

// Enum value maps for ResultCode.
var (
	ResultCode_name = map[int32]string{
		0: "RESULT_CODE_UNSPECIFIED",
		1: "RESULT_CODE_ACCEPTED",
		2: "RESULT_CODE_INCOMPATIBLE_VERSION",
		3: "RESULT_CODE_MISSING_REQUIRED_FEATURE",
		4: "RESULT_CODE_INVALID_PARAMETER",
		5: "RESULT_CODE_SESSION_COLLISION",
	}
	ResultCode_value = map[string]int32{
		"RESULT_CODE_UNSPECIFIED":              0,
		"RESULT_CODE_ACCEPTED":                 1,
		"RESULT_CODE_INCOMPATIBLE_VERSION":     2,
		"RESULT_CODE_MISSING_REQUIRED_FEATURE": 3,
		"RESULT_CODE_INVALID_PARAMETER":        4,
		"RESULT_CODE_SESSION_COLLISION":        5,
	}
)

func (x ResultCode) Enum() *ResultCode {
	p := new(ResultCode)
	*p = x
	return p
}

func (x ResultCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultCode) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_v1_control_proto_enumTypes[0].Descriptor()
}

func (ResultCode) Type() protoreflect.EnumType {
	return &file_wire_v1_control_proto_enumTypes[0]
}

func (x ResultCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type StateSyncRequired_Reason int32

const (
	StateSyncRequired_REASON_UNSPECIFIED          StateSyncRequired_Reason = 0
	StateSyncRequired_REASON_UNKNOWN_DATA_SESSION StateSyncRequired_Reason = 1
)

// Enum value maps for StateSyncRequired_Reason.
var (
	StateSyncRequired_Reason_name = map[int32]string{
		0: "REASON_UNSPECIFIED",
		1: "REASON_UNKNOWN_DATA_SESSION",
	}
	StateSyncRequired_Reason_value = map[string]int32{
		"REASON_UNSPECIFIED":          0,
		"REASON_UNKNOWN_DATA_SESSION": 1,
	}
)

func (x StateSyncRequired_Reason) Enum() *StateSyncRequired_Reason {
	p := new(StateSyncRequired_Reason)
	*p = x
	return p
}

func (x StateSyncRequired_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateSyncRequired_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_v1_control_proto_enumTypes[1].Descriptor()
}

func (StateSyncRequired_Reason) Type() protoreflect.EnumType {
	return &file_wire_v1_control_proto_enumTypes[1]
}

func (x StateSyncRequired_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Control is carried inside a standalone WGF CONTROL carrier frame.
type Control struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MessageId    uint64                 `protobuf:"varint,1,opt,name=message_id,json=messageId"`
	xxx_hidden_ReplyTo      uint64                 `protobuf:"varint,2,opt,name=reply_to,json=replyTo"`
	xxx_hidden_ControlEpoch uint64                 `protobuf:"varint,3,opt,name=control_epoch,json=controlEpoch"`
	xxx_hidden_Padding      []byte                 `protobuf:"bytes,4,opt,name=padding"`
	xxx_hidden_Body         isControl_Body         `protobuf_oneof:"body"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_wire_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Control) GetMessageId() uint64 {
	if x != nil {
		return x.xxx_hidden_MessageId
	}
	return 0
}

func (x *Control) GetReplyTo() uint64 {
	if x != nil {
		return x.xxx_hidden_ReplyTo
	}
	return 0
}

func (x *Control) GetControlEpoch() uint64 {
	if x != nil {
		return x.xxx_hidden_ControlEpoch
	}
	return 0
}

func (x *Control) GetPadding() []byte {
	if x != nil {
		return x.xxx_hidden_Padding
	}
	return nil
}

func (x *Control) GetCapabilitiesHello() *CapabilitiesHello {
	if x != nil {
		if x, ok := x.xxx_hidden_Body.(*control_CapabilitiesHello); ok {
			return x.CapabilitiesHello
		}
	}
	return nil
}

func (x *Control) GetMtuProbe() *MtuProbe {
	if x != nil {
		if x, ok := x.xxx_hidden_Body.(*control_MtuProbe); ok {
			return x.MtuProbe
		}
	}
	return nil
}

func (x *Control) GetMtuProbeAck() *MtuProbeAck {
	if x != nil {
		if x, ok := x.xxx_hidden_Body.(*control_MtuProbeAck); ok {
			return x.MtuProbeAck
		}
	}
	return nil
}

func (x *Control) GetPing() *Ping {
	if x != nil {
		if x, ok := x.xxx_hidden_Body.(*control_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Control) GetPong() *Pong {
	if x != nil {
		if x, ok := x.xxx_hidden_Body.(*control_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Control) GetCapabilitiesAck() *CapabilitiesAck {
	if x != nil {
		if x, ok := x.xxx_hidden_Body.(*control_CapabilitiesAck); ok {
			return x.CapabilitiesAck
		}
	}
	return nil
}

func (x *Control) GetResetSequence() *ResetSequence {
	if x != nil {
		if x, ok := x.xxx_hidden_Body.(*control_ResetSequence); ok {
			return x.ResetSequence
		}
	}
	return nil
}

func (x *Control) GetResetSequenceAck() *ResetSequenceAck {
	if x != nil {
		if x, ok := x.xxx_hidden_Body.(*control_ResetSequenceAck); ok {
			return x.ResetSequenceAck
		}
	}
	return nil
}

func (x *Control) GetPeerMtu() *PeerMTU {
	if x != nil {
		if x, ok := x.xxx_hidden_Body.(*control_PeerMtu); ok {
			return x.PeerMtu
		}
	}
	return nil
}

func (x *Control) GetPeerMtuAck() *PeerMTUAck {
	if x != nil {
		if x, ok := x.xxx_hidden_Body.(*control_PeerMtuAck); ok {
			return x.PeerMtuAck
		}
	}
	return nil
}

func (x *Control) GetStateSyncRequired() *StateSyncRequired {
	if x != nil {
		if x, ok := x.xxx_hidden_Body.(*control_StateSyncRequired); ok {
			return x.StateSyncRequired
		}
	}
	return nil
}

func (x *Control) SetMessageId(v uint64) {
	x.xxx_hidden_MessageId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Control) SetReplyTo(v uint64) {
	x.xxx_hidden_ReplyTo = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Control) SetControlEpoch(v uint64) {
	x.xxx_hidden_ControlEpoch = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *Control) SetPadding(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Padding = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *Control) SetCapabilitiesHello(v *CapabilitiesHello) {
	if v == nil {
		x.xxx_hidden_Body = nil
		return
	}
	x.xxx_hidden_Body = &control_CapabilitiesHello{v}
}

func (x *Control) SetMtuProbe(v *MtuProbe) {
	if v == nil {
		x.xxx_hidden_Body = nil
		return
	}
	x.xxx_hidden_Body = &control_MtuProbe{v}
}

func (x *Control) SetMtuProbeAck(v *MtuProbeAck) {
	if v == nil {
		x.xxx_hidden_Body = nil
		return
	}
	x.xxx_hidden_Body = &control_MtuProbeAck{v}
}

func (x *Control) SetPing(v *Ping) {
	if v == nil {
		x.xxx_hidden_Body = nil
		return
	}
	x.xxx_hidden_Body = &control_Ping{v}
}

func (x *Control) SetPong(v *Pong) {
	if v == nil {
		x.xxx_hidden_Body = nil
		return
	}
	x.xxx_hidden_Body = &control_Pong{v}
}

func (x *Control) SetCapabilitiesAck(v *CapabilitiesAck) {
	if v == nil {
		x.xxx_hidden_Body = nil
		return
	}
	x.xxx_hidden_Body = &control_CapabilitiesAck{v}
}

func (x *Control) SetResetSequence(v *ResetSequence) {
	if v == nil {
		x.xxx_hidden_Body = nil
		return
	}
	x.xxx_hidden_Body = &control_ResetSequence{v}
}

func (x *Control) SetResetSequenceAck(v *ResetSequenceAck) {
	if v == nil {
		x.xxx_hidden_Body = nil
		return
	}
	x.xxx_hidden_Body = &control_ResetSequenceAck{v}
}

func (x *Control) SetPeerMtu(v *PeerMTU) {
	if v == nil {
		x.xxx_hidden_Body = nil
		return
	}
	x.xxx_hidden_Body = &control_PeerMtu{v}
}

func (x *Control) SetPeerMtuAck(v *PeerMTUAck) {
	if v == nil {
		x.xxx_hidden_Body = nil
		return
	}
	x.xxx_hidden_Body = &control_PeerMtuAck{v}
}

func (x *Control) SetStateSyncRequired(v *StateSyncRequired) {
	if v == nil {
		x.xxx_hidden_Body = nil
		return
	}
	x.xxx_hidden_Body = &control_StateSyncRequired{v}
}

func (x *Control) HasMessageId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Control) HasReplyTo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Control) HasControlEpoch() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Control) HasPadding() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Control) HasBody() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Body != nil
}

func (x *Control) HasCapabilitiesHello() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Body.(*control_CapabilitiesHello)
	return ok
}

func (x *Control) HasMtuProbe() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Body.(*control_MtuProbe)
	return ok
}

func (x *Control) HasMtuProbeAck() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Body.(*control_MtuProbeAck)
	return ok
}

func (x *Control) HasPing() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Body.(*control_Ping)
	return ok
}

func (x *Control) HasPong() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Body.(*control_Pong)
	return ok
}

func (x *Control) HasCapabilitiesAck() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Body.(*control_CapabilitiesAck)
	return ok
}

func (x *Control) HasResetSequence() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Body.(*control_ResetSequence)
	return ok
}

func (x *Control) HasResetSequenceAck() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Body.(*control_ResetSequenceAck)
	return ok
}

func (x *Control) HasPeerMtu() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Body.(*control_PeerMtu)
	return ok
}

func (x *Control) HasPeerMtuAck() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Body.(*control_PeerMtuAck)
	return ok
}

func (x *Control) HasStateSyncRequired() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Body.(*control_StateSyncRequired)
	return ok
}

func (x *Control) ClearMessageId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_MessageId = 0
}

func (x *Control) ClearReplyTo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ReplyTo = 0
}

func (x *Control) ClearControlEpoch() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ControlEpoch = 0
}

func (x *Control) ClearPadding() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Padding = nil
}

func (x *Control) ClearBody() {
	x.xxx_hidden_Body = nil
}

func (x *Control) ClearCapabilitiesHello() {
	if _, ok := x.xxx_hidden_Body.(*control_CapabilitiesHello); ok {
		x.xxx_hidden_Body = nil
	}
}

func (x *Control) ClearMtuProbe() {
	if _, ok := x.xxx_hidden_Body.(*control_MtuProbe); ok {
		x.xxx_hidden_Body = nil
	}
}

func (x *Control) ClearMtuProbeAck() {
	if _, ok := x.xxx_hidden_Body.(*control_MtuProbeAck); ok {
		x.xxx_hidden_Body = nil
	}
}

func (x *Control) ClearPing() {
	if _, ok := x.xxx_hidden_Body.(*control_Ping); ok {
		x.xxx_hidden_Body = nil
	}
}

func (x *Control) ClearPong() {
	if _, ok := x.xxx_hidden_Body.(*control_Pong); ok {
		x.xxx_hidden_Body = nil
	}
}

func (x *Control) ClearCapabilitiesAck() {
	if _, ok := x.xxx_hidden_Body.(*control_CapabilitiesAck); ok {
		x.xxx_hidden_Body = nil
	}
}

func (x *Control) ClearResetSequence() {
	if _, ok := x.xxx_hidden_Body.(*control_ResetSequence); ok {
		x.xxx_hidden_Body = nil
	}
}

func (x *Control) ClearResetSequenceAck() {
	if _, ok := x.xxx_hidden_Body.(*control_ResetSequenceAck); ok {
		x.xxx_hidden_Body = nil
	}
}

func (x *Control) ClearPeerMtu() {
	if _, ok := x.xxx_hidden_Body.(*control_PeerMtu); ok {
		x.xxx_hidden_Body = nil
	}
}

func (x *Control) ClearPeerMtuAck() {
	if _, ok := x.xxx_hidden_Body.(*control_PeerMtuAck); ok {
		x.xxx_hidden_Body = nil
	}
}

func (x *Control) ClearStateSyncRequired() {
	if _, ok := x.xxx_hidden_Body.(*control_StateSyncRequired); ok {
		x.xxx_hidden_Body = nil
	}
}

const Control_Body_not_set_case case_Control_Body = 0
const Control_CapabilitiesHello_case case_Control_Body = 10
const Control_MtuProbe_case case_Control_Body = 11
const Control_MtuProbeAck_case case_Control_Body = 12
const Control_Ping_case case_Control_Body = 13
const Control_Pong_case case_Control_Body = 14
const Control_CapabilitiesAck_case case_Control_Body = 15
const Control_ResetSequence_case case_Control_Body = 16
const Control_ResetSequenceAck_case case_Control_Body = 17
const Control_PeerMtu_case case_Control_Body = 18
const Control_PeerMtuAck_case case_Control_Body = 19
const Control_StateSyncRequired_case case_Control_Body = 20

func (x *Control) WhichBody() case_Control_Body {
	if x == nil {
		return Control_Body_not_set_case
	}
	switch x.xxx_hidden_Body.(type) {
	case *control_CapabilitiesHello:
		return Control_CapabilitiesHello_case
	case *control_MtuProbe:
		return Control_MtuProbe_case
	case *control_MtuProbeAck:
		return Control_MtuProbeAck_case
	case *control_Ping:
		return Control_Ping_case
	case *control_Pong:
		return Control_Pong_case
	case *control_CapabilitiesAck:
		return Control_CapabilitiesAck_case
	case *control_ResetSequence:
		return Control_ResetSequence_case
	case *control_ResetSequenceAck:
		return Control_ResetSequenceAck_case
	case *control_PeerMtu:
		return Control_PeerMtu_case
	case *control_PeerMtuAck:
		return Control_PeerMtuAck_case
	case *control_StateSyncRequired:
		return Control_StateSyncRequired_case
	default:
		return Control_Body_not_set_case
	}
}

type Control_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Non-zero and unique within control_epoch.
	MessageId *uint64
	// Responses set this to the request message_id; requests set zero.
	ReplyTo *uint64
	// Non-zero random value generated per process and send direction.
	ControlEpoch *uint64
	// Used only by MtuProbe to reach a candidate carrier payload size.
	Padding []byte
	// Fields of oneof xxx_hidden_Body:
	CapabilitiesHello *CapabilitiesHello
	MtuProbe          *MtuProbe
	MtuProbeAck       *MtuProbeAck
	Ping              *Ping
	Pong              *Pong
	CapabilitiesAck   *CapabilitiesAck
	ResetSequence     *ResetSequence
	ResetSequenceAck  *ResetSequenceAck
	PeerMtu           *PeerMTU
	PeerMtuAck        *PeerMTUAck
	StateSyncRequired *StateSyncRequired
	// -- end of xxx_hidden_Body
}

func (b0 Control_builder) Build() *Control {
	m0 := &Control{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MessageId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_MessageId = *b.MessageId
	}
	if b.ReplyTo != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_ReplyTo = *b.ReplyTo
	}
	if b.ControlEpoch != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_ControlEpoch = *b.ControlEpoch
	}
	if b.Padding != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Padding = b.Padding
	}
	if b.CapabilitiesHello != nil {
		x.xxx_hidden_Body = &control_CapabilitiesHello{b.CapabilitiesHello}
	}
	if b.MtuProbe != nil {
		x.xxx_hidden_Body = &control_MtuProbe{b.MtuProbe}
	}
	if b.MtuProbeAck != nil {
		x.xxx_hidden_Body = &control_MtuProbeAck{b.MtuProbeAck}
	}
	if b.Ping != nil {
		x.xxx_hidden_Body = &control_Ping{b.Ping}
	}
	if b.Pong != nil {
		x.xxx_hidden_Body = &control_Pong{b.Pong}
	}
	if b.CapabilitiesAck != nil {
		x.xxx_hidden_Body = &control_CapabilitiesAck{b.CapabilitiesAck}
	}
	if b.ResetSequence != nil {
		x.xxx_hidden_Body = &control_ResetSequence{b.ResetSequence}
	}
	if b.ResetSequenceAck != nil {
		x.xxx_hidden_Body = &control_ResetSequenceAck{b.ResetSequenceAck}
	}
	if b.PeerMtu != nil {
		x.xxx_hidden_Body = &control_PeerMtu{b.PeerMtu}
	}
	if b.PeerMtuAck != nil {
		x.xxx_hidden_Body = &control_PeerMtuAck{b.PeerMtuAck}
	}
	if b.StateSyncRequired != nil {
		x.xxx_hidden_Body = &control_StateSyncRequired{b.StateSyncRequired}
	}
	return m0
}

type case_Control_Body protoreflect.FieldNumber

func (x case_Control_Body) String() string {
	md := file_wire_v1_control_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isControl_Body interface {
	isControl_Body()
}

type control_CapabilitiesHello struct {
	CapabilitiesHello *CapabilitiesHello `protobuf:"bytes,10,opt,name=capabilities_hello,json=capabilitiesHello,oneof"`
}

type control_MtuProbe struct {
	MtuProbe *MtuProbe `protobuf:"bytes,11,opt,name=mtu_probe,json=mtuProbe,oneof"`
}

type control_MtuProbeAck struct {
	MtuProbeAck *MtuProbeAck `protobuf:"bytes,12,opt,name=mtu_probe_ack,json=mtuProbeAck,oneof"`
}

type control_Ping struct {
	Ping *Ping `protobuf:"bytes,13,opt,name=ping,oneof"`
}

type control_Pong struct {
	Pong *Pong `protobuf:"bytes,14,opt,name=pong,oneof"`
}

type control_CapabilitiesAck struct {
	CapabilitiesAck *CapabilitiesAck `protobuf:"bytes,15,opt,name=capabilities_ack,json=capabilitiesAck,oneof"`
}

type control_ResetSequence struct {
	ResetSequence *ResetSequence `protobuf:"bytes,16,opt,name=reset_sequence,json=resetSequence,oneof"`
}

type control_ResetSequenceAck struct {
	ResetSequenceAck *ResetSequenceAck `protobuf:"bytes,17,opt,name=reset_sequence_ack,json=resetSequenceAck,oneof"`
}

type control_PeerMtu struct {
	PeerMtu *PeerMTU `protobuf:"bytes,18,opt,name=peer_mtu,json=peerMtu,oneof"`
}

type control_PeerMtuAck struct {
	PeerMtuAck *PeerMTUAck `protobuf:"bytes,19,opt,name=peer_mtu_ack,json=peerMtuAck,oneof"`
}

type control_StateSyncRequired struct {
	StateSyncRequired *StateSyncRequired `protobuf:"bytes,20,opt,name=state_sync_required,json=stateSyncRequired,oneof"`
}

func (*control_CapabilitiesHello) isControl_Body() {}

func (*control_MtuProbe) isControl_Body() {}

func (*control_MtuProbeAck) isControl_Body() {}

func (*control_Ping) isControl_Body() {}

func (*control_Pong) isControl_Body() {}

func (*control_CapabilitiesAck) isControl_Body() {}

func (*control_ResetSequence) isControl_Body() {}

func (*control_ResetSequenceAck) isControl_Body() {}

func (*control_PeerMtu) isControl_Body() {}

func (*control_PeerMtuAck) isControl_Body() {}

func (*control_StateSyncRequired) isControl_Body() {}

type CapabilitiesHello struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DataProtocolVersion  uint32                 `protobuf:"varint,1,opt,name=data_protocol_version,json=dataProtocolVersion"`
	xxx_hidden_MaxFragments         uint32                 `protobuf:"varint,2,opt,name=max_fragments,json=maxFragments"`
	xxx_hidden_MaxCarrierPayload    uint32                 `protobuf:"varint,3,opt,name=max_carrier_payload,json=maxCarrierPayload"`
	xxx_hidden_SupportedFeatureBits uint64                 `protobuf:"varint,4,opt,name=supported_feature_bits,json=supportedFeatureBits"`
	xxx_hidden_RequiredFeatureBits  uint64                 `protobuf:"varint,5,opt,name=required_feature_bits,json=requiredFeatureBits"`
	xxx_hidden_ReassemblyLifetimeMs uint32                 `protobuf:"varint,6,opt,name=reassembly_lifetime_ms,json=reassemblyLifetimeMs"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *CapabilitiesHello) Reset() {
	*x = CapabilitiesHello{}
	mi := &file_wire_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesHello) ProtoMessage() {}

func (x *CapabilitiesHello) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CapabilitiesHello) GetDataProtocolVersion() uint32 {
	if x != nil {
		return x.xxx_hidden_DataProtocolVersion
	}
	return 0
}

func (x *CapabilitiesHello) GetMaxFragments() uint32 {
	if x != nil {
		return x.xxx_hidden_MaxFragments
	}
	return 0
}

func (x *CapabilitiesHello) GetMaxCarrierPayload() uint32 {
	if x != nil {
		return x.xxx_hidden_MaxCarrierPayload
	}
	return 0
}

func (x *CapabilitiesHello) GetSupportedFeatureBits() uint64 {
	if x != nil {
		return x.xxx_hidden_SupportedFeatureBits
	}
	return 0
}

func (x *CapabilitiesHello) GetRequiredFeatureBits() uint64 {
	if x != nil {
		return x.xxx_hidden_RequiredFeatureBits
	}
	return 0
}

func (x *CapabilitiesHello) GetReassemblyLifetimeMs() uint32 {
	if x != nil {
		return x.xxx_hidden_ReassemblyLifetimeMs
	}
	return 0
}

func (x *CapabilitiesHello) SetDataProtocolVersion(v uint32) {
	x.xxx_hidden_DataProtocolVersion = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *CapabilitiesHello) SetMaxFragments(v uint32) {
	x.xxx_hidden_MaxFragments = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *CapabilitiesHello) SetMaxCarrierPayload(v uint32) {
	x.xxx_hidden_MaxCarrierPayload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *CapabilitiesHello) SetSupportedFeatureBits(v uint64) {
	x.xxx_hidden_SupportedFeatureBits = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *CapabilitiesHello) SetRequiredFeatureBits(v uint64) {
	x.xxx_hidden_RequiredFeatureBits = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *CapabilitiesHello) SetReassemblyLifetimeMs(v uint32) {
	x.xxx_hidden_ReassemblyLifetimeMs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *CapabilitiesHello) HasDataProtocolVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CapabilitiesHello) HasMaxFragments() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CapabilitiesHello) HasMaxCarrierPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CapabilitiesHello) HasSupportedFeatureBits() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CapabilitiesHello) HasRequiredFeatureBits() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CapabilitiesHello) HasReassemblyLifetimeMs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *CapabilitiesHello) ClearDataProtocolVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DataProtocolVersion = 0
}

func (x *CapabilitiesHello) ClearMaxFragments() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_MaxFragments = 0
}

func (x *CapabilitiesHello) ClearMaxCarrierPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_MaxCarrierPayload = 0
}

func (x *CapabilitiesHello) ClearSupportedFeatureBits() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_SupportedFeatureBits = 0
}

func (x *CapabilitiesHello) ClearRequiredFeatureBits() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_RequiredFeatureBits = 0
}

func (x *CapabilitiesHello) ClearReassemblyLifetimeMs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_ReassemblyLifetimeMs = 0
}

type CapabilitiesHello_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DataProtocolVersion  *uint32
	MaxFragments         *uint32
	MaxCarrierPayload    *uint32
	SupportedFeatureBits *uint64
	RequiredFeatureBits  *uint64
	ReassemblyLifetimeMs *uint32
}

func (b0 CapabilitiesHello_builder) Build() *CapabilitiesHello {
	m0 := &CapabilitiesHello{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DataProtocolVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_DataProtocolVersion = *b.DataProtocolVersion
	}
	if b.MaxFragments != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_MaxFragments = *b.MaxFragments
	}
	if b.MaxCarrierPayload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_MaxCarrierPayload = *b.MaxCarrierPayload
	}
	if b.SupportedFeatureBits != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_SupportedFeatureBits = *b.SupportedFeatureBits
	}
	if b.RequiredFeatureBits != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_RequiredFeatureBits = *b.RequiredFeatureBits
	}
	if b.ReassemblyLifetimeMs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_ReassemblyLifetimeMs = *b.ReassemblyLifetimeMs
	}
	return m0
}

type CapabilitiesAck struct {
	state                                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SelectedDataProtocolVersion uint32                 `protobuf:"varint,1,opt,name=selected_data_protocol_version,json=selectedDataProtocolVersion"`
	xxx_hidden_SelectedFeatureBits         uint64                 `protobuf:"varint,2,opt,name=selected_feature_bits,json=selectedFeatureBits"`
	xxx_hidden_Result                      ResultCode             `protobuf:"varint,3,opt,name=result,enum=wgf.protocol.wire.v1.ResultCode"`
	XXX_raceDetectHookData                 protoimpl.RaceDetectHookData
	XXX_presence                           [1]uint32
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *CapabilitiesAck) Reset() {
	*x = CapabilitiesAck{}
	mi := &file_wire_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesAck) ProtoMessage() {}

func (x *CapabilitiesAck) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CapabilitiesAck) GetSelectedDataProtocolVersion() uint32 {
	if x != nil {
		return x.xxx_hidden_SelectedDataProtocolVersion
	}
	return 0
}

func (x *CapabilitiesAck) GetSelectedFeatureBits() uint64 {
	if x != nil {
		return x.xxx_hidden_SelectedFeatureBits
	}
	return 0
}

func (x *CapabilitiesAck) GetResult() ResultCode {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Result
		}
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *CapabilitiesAck) SetSelectedDataProtocolVersion(v uint32) {
	x.xxx_hidden_SelectedDataProtocolVersion = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *CapabilitiesAck) SetSelectedFeatureBits(v uint64) {
	x.xxx_hidden_SelectedFeatureBits = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *CapabilitiesAck) SetResult(v ResultCode) {
	x.xxx_hidden_Result = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *CapabilitiesAck) HasSelectedDataProtocolVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CapabilitiesAck) HasSelectedFeatureBits() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CapabilitiesAck) HasResult() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CapabilitiesAck) ClearSelectedDataProtocolVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_SelectedDataProtocolVersion = 0
}

func (x *CapabilitiesAck) ClearSelectedFeatureBits() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_SelectedFeatureBits = 0
}

func (x *CapabilitiesAck) ClearResult() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Result = ResultCode_RESULT_CODE_UNSPECIFIED
}

type CapabilitiesAck_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SelectedDataProtocolVersion *uint32
	SelectedFeatureBits         *uint64
	Result                      *ResultCode
}

func (b0 CapabilitiesAck_builder) Build() *CapabilitiesAck {
	m0 := &CapabilitiesAck{}
	b, x := &b0, m0
	_, _ = b, x
	if b.SelectedDataProtocolVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_SelectedDataProtocolVersion = *b.SelectedDataProtocolVersion
	}
	if b.SelectedFeatureBits != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_SelectedFeatureBits = *b.SelectedFeatureBits
	}
	if b.Result != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Result = *b.Result
	}
	return m0
}

type MtuProbe struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MtuProbe) Reset() {
	*x = MtuProbe{}
	mi := &file_wire_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MtuProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MtuProbe) ProtoMessage() {}

func (x *MtuProbe) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type MtuProbe_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 MtuProbe_builder) Build() *MtuProbe {
	m0 := &MtuProbe{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type MtuProbeAck struct {
	state                               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ReceivedProbePayloadSize uint32                 `protobuf:"varint,1,opt,name=received_probe_payload_size,json=receivedProbePayloadSize"`
	XXX_raceDetectHookData              protoimpl.RaceDetectHookData
	XXX_presence                        [1]uint32
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *MtuProbeAck) Reset() {
	*x = MtuProbeAck{}
	mi := &file_wire_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MtuProbeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MtuProbeAck) ProtoMessage() {}

func (x *MtuProbeAck) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MtuProbeAck) GetReceivedProbePayloadSize() uint32 {
	if x != nil {
		return x.xxx_hidden_ReceivedProbePayloadSize
	}
	return 0
}

func (x *MtuProbeAck) SetReceivedProbePayloadSize(v uint32) {
	x.xxx_hidden_ReceivedProbePayloadSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *MtuProbeAck) HasReceivedProbePayloadSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MtuProbeAck) ClearReceivedProbePayloadSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ReceivedProbePayloadSize = 0
}

type MtuProbeAck_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ReceivedProbePayloadSize *uint32
}

func (b0 MtuProbeAck_builder) Build() *MtuProbeAck {
	m0 := &MtuProbeAck{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ReceivedProbePayloadSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ReceivedProbePayloadSize = *b.ReceivedProbePayloadSize
	}
	return m0
}

type ResetSequence struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DataSessionId uint32                 `protobuf:"varint,1,opt,name=data_session_id,json=dataSessionId"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ResetSequence) Reset() {
	*x = ResetSequence{}
	mi := &file_wire_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetSequence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetSequence) ProtoMessage() {}

func (x *ResetSequence) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResetSequence) GetDataSessionId() uint32 {
	if x != nil {
		return x.xxx_hidden_DataSessionId
	}
	return 0
}

func (x *ResetSequence) SetDataSessionId(v uint32) {
	x.xxx_hidden_DataSessionId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ResetSequence) HasDataSessionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ResetSequence) ClearDataSessionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DataSessionId = 0
}

type ResetSequence_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Valid range: 1..65535.
	DataSessionId *uint32
}

func (b0 ResetSequence_builder) Build() *ResetSequence {
	m0 := &ResetSequence{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DataSessionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_DataSessionId = *b.DataSessionId
	}
	return m0
}

type ResetSequenceAck struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DataSessionId uint32                 `protobuf:"varint,1,opt,name=data_session_id,json=dataSessionId"`
	xxx_hidden_Result        ResultCode             `protobuf:"varint,2,opt,name=result,enum=wgf.protocol.wire.v1.ResultCode"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ResetSequenceAck) Reset() {
	*x = ResetSequenceAck{}
	mi := &file_wire_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetSequenceAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetSequenceAck) ProtoMessage() {}

func (x *ResetSequenceAck) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResetSequenceAck) GetDataSessionId() uint32 {
	if x != nil {
		return x.xxx_hidden_DataSessionId
	}
	return 0
}

func (x *ResetSequenceAck) GetResult() ResultCode {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Result
		}
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *ResetSequenceAck) SetDataSessionId(v uint32) {
	x.xxx_hidden_DataSessionId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ResetSequenceAck) SetResult(v ResultCode) {
	x.xxx_hidden_Result = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ResetSequenceAck) HasDataSessionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ResetSequenceAck) HasResult() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ResetSequenceAck) ClearDataSessionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DataSessionId = 0
}

func (x *ResetSequenceAck) ClearResult() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Result = ResultCode_RESULT_CODE_UNSPECIFIED
}

type ResetSequenceAck_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DataSessionId *uint32
	Result        *ResultCode
}

func (b0 ResetSequenceAck_builder) Build() *ResetSequenceAck {
	m0 := &ResetSequenceAck{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DataSessionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_DataSessionId = *b.DataSessionId
	}
	if b.Result != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Result = *b.Result
	}
	return m0
}

type PeerMTU struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InnerMtu    uint32                 `protobuf:"varint,1,opt,name=inner_mtu,json=innerMtu"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PeerMTU) Reset() {
	*x = PeerMTU{}
	mi := &file_wire_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMTU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMTU) ProtoMessage() {}

func (x *PeerMTU) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PeerMTU) GetInnerMtu() uint32 {
	if x != nil {
		return x.xxx_hidden_InnerMtu
	}
	return 0
}

func (x *PeerMTU) SetInnerMtu(v uint32) {
	x.xxx_hidden_InnerMtu = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *PeerMTU) HasInnerMtu() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PeerMTU) ClearInnerMtu() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_InnerMtu = 0
}

type PeerMTU_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	InnerMtu *uint32
}

func (b0 PeerMTU_builder) Build() *PeerMTU {
	m0 := &PeerMTU{}
	b, x := &b0, m0
	_, _ = b, x
	if b.InnerMtu != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_InnerMtu = *b.InnerMtu
	}
	return m0
}

type PeerMTUAck struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InnerMtu    uint32                 `protobuf:"varint,1,opt,name=inner_mtu,json=innerMtu"`
	xxx_hidden_Result      ResultCode             `protobuf:"varint,2,opt,name=result,enum=wgf.protocol.wire.v1.ResultCode"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PeerMTUAck) Reset() {
	*x = PeerMTUAck{}
	mi := &file_wire_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMTUAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMTUAck) ProtoMessage() {}

func (x *PeerMTUAck) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PeerMTUAck) GetInnerMtu() uint32 {
	if x != nil {
		return x.xxx_hidden_InnerMtu
	}
	return 0
}

func (x *PeerMTUAck) GetResult() ResultCode {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Result
		}
	}
	return ResultCode_RESULT_CODE_UNSPECIFIED
}

func (x *PeerMTUAck) SetInnerMtu(v uint32) {
	x.xxx_hidden_InnerMtu = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *PeerMTUAck) SetResult(v ResultCode) {
	x.xxx_hidden_Result = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *PeerMTUAck) HasInnerMtu() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PeerMTUAck) HasResult() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PeerMTUAck) ClearInnerMtu() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_InnerMtu = 0
}

func (x *PeerMTUAck) ClearResult() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Result = ResultCode_RESULT_CODE_UNSPECIFIED
}

type PeerMTUAck_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	InnerMtu *uint32
	Result   *ResultCode
}

func (b0 PeerMTUAck_builder) Build() *PeerMTUAck {
	m0 := &PeerMTUAck{}
	b, x := &b0, m0
	_, _ = b, x
	if b.InnerMtu != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_InnerMtu = *b.InnerMtu
	}
	if b.Result != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Result = *b.Result
	}
	return m0
}

type Ping struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Sequence    uint32                 `protobuf:"varint,1,opt,name=sequence"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_wire_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Ping) GetSequence() uint32 {
	if x != nil {
		return x.xxx_hidden_Sequence
	}
	return 0
}

func (x *Ping) SetSequence(v uint32) {
	x.xxx_hidden_Sequence = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Ping) HasSequence() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Ping) ClearSequence() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Sequence = 0
}

type Ping_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Sequence *uint32
}

func (b0 Ping_builder) Build() *Ping {
	m0 := &Ping{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Sequence != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Sequence = *b.Sequence
	}
	return m0
}

type Pong struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Sequence    uint32                 `protobuf:"varint,1,opt,name=sequence"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_wire_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Pong) GetSequence() uint32 {
	if x != nil {
		return x.xxx_hidden_Sequence
	}
	return 0
}

func (x *Pong) SetSequence(v uint32) {
	x.xxx_hidden_Sequence = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Pong) HasSequence() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Pong) ClearSequence() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Sequence = 0
}

type Pong_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Sequence *uint32
}

func (b0 Pong_builder) Build() *Pong {
	m0 := &Pong{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Sequence != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Sequence = *b.Sequence
	}
	return m0
}

type StateSyncRequired struct {
	state                            protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Reason                StateSyncRequired_Reason `protobuf:"varint,1,opt,name=reason,enum=wgf.protocol.wire.v1.StateSyncRequired_Reason"`
	xxx_hidden_ObservedDataSessionId uint32                   `protobuf:"varint,2,opt,name=observed_data_session_id,json=observedDataSessionId"`
	XXX_raceDetectHookData           protoimpl.RaceDetectHookData
	XXX_presence                     [1]uint32
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *StateSyncRequired) Reset() {
	*x = StateSyncRequired{}
	mi := &file_wire_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSyncRequired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSyncRequired) ProtoMessage() {}

func (x *StateSyncRequired) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StateSyncRequired) GetReason() StateSyncRequired_Reason {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Reason
		}
	}
	return StateSyncRequired_REASON_UNSPECIFIED
}

func (x *StateSyncRequired) GetObservedDataSessionId() uint32 {
	if x != nil {
		return x.xxx_hidden_ObservedDataSessionId
	}
	return 0
}

func (x *StateSyncRequired) SetReason(v StateSyncRequired_Reason) {
	x.xxx_hidden_Reason = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *StateSyncRequired) SetObservedDataSessionId(v uint32) {
	x.xxx_hidden_ObservedDataSessionId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *StateSyncRequired) HasReason() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StateSyncRequired) HasObservedDataSessionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StateSyncRequired) ClearReason() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Reason = StateSyncRequired_REASON_UNSPECIFIED
}

func (x *StateSyncRequired) ClearObservedDataSessionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ObservedDataSessionId = 0
}

type StateSyncRequired_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Reason                *StateSyncRequired_Reason
	ObservedDataSessionId *uint32
}

func (b0 StateSyncRequired_builder) Build() *StateSyncRequired {
	m0 := &StateSyncRequired{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Reason != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Reason = *b.Reason
	}
	if b.ObservedDataSessionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ObservedDataSessionId = *b.ObservedDataSessionId
	}
	return m0
}

var File_wire_v1_control_proto protoreflect.FileDescriptor

const file_wire_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x15wire/v1/control.proto\x12\x14wgf.protocol.wire.v1\"\xa7\a\n" +
	"\aControl\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x04R\tmessageId\x12\x19\n" +
	"\breply_to\x18\x02 \x01(\x04R\areplyTo\x12#\n" +
	"\rcontrol_epoch\x18\x03 \x01(\x04R\fcontrolEpoch\x12\x18\n" +
	"\apadding\x18\x04 \x01(\fR\apadding\x12X\n" +
	"\x12capabilities_hello\x18\n" +
	" \x01(\v2'.wgf.protocol.wire.v1.CapabilitiesHelloH\x00R\x11capabilitiesHello\x12=\n" +
	"\tmtu_probe\x18\v \x01(\v2\x1e.wgf.protocol.wire.v1.MtuProbeH\x00R\bmtuProbe\x12G\n" +
	"\rmtu_probe_ack\x18\f \x01(\v2!.wgf.protocol.wire.v1.MtuProbeAckH\x00R\vmtuProbeAck\x120\n" +
	"\x04ping\x18\r \x01(\v2\x1a.wgf.protocol.wire.v1.PingH\x00R\x04ping\x120\n" +
	"\x04pong\x18\x0e \x01(\v2\x1a.wgf.protocol.wire.v1.PongH\x00R\x04pong\x12R\n" +
	"\x10capabilities_ack\x18\x0f \x01(\v2%.wgf.protocol.wire.v1.CapabilitiesAckH\x00R\x0fcapabilitiesAck\x12L\n" +
	"\x0ereset_sequence\x18\x10 \x01(\v2#.wgf.protocol.wire.v1.ResetSequenceH\x00R\rresetSequence\x12V\n" +
	"\x12reset_sequence_ack\x18\x11 \x01(\v2&.wgf.protocol.wire.v1.ResetSequenceAckH\x00R\x10resetSequenceAck\x12:\n" +
	"\bpeer_mtu\x18\x12 \x01(\v2\x1d.wgf.protocol.wire.v1.PeerMTUH\x00R\apeerMtu\x12D\n" +
	"\fpeer_mtu_ack\x18\x13 \x01(\v2 .wgf.protocol.wire.v1.PeerMTUAckH\x00R\n" +
	"peerMtuAck\x12Y\n" +
	"\x13state_sync_required\x18\x14 \x01(\v2'.wgf.protocol.wire.v1.StateSyncRequiredH\x00R\x11stateSyncRequiredB\x06\n" +
	"\x04body\"\xbc\x02\n" +
	"\x11CapabilitiesHello\x122\n" +
	"\x15data_protocol_version\x18\x01 \x01(\rR\x13dataProtocolVersion\x12#\n" +
	"\rmax_fragments\x18\x02 \x01(\rR\fmaxFragments\x12.\n" +
	"\x13max_carrier_payload\x18\x03 \x01(\rR\x11maxCarrierPayload\x124\n" +
	"\x16supported_feature_bits\x18\x04 \x01(\x04R\x14supportedFeatureBits\x122\n" +
	"\x15required_feature_bits\x18\x05 \x01(\x04R\x13requiredFeatureBits\x124\n" +
	"\x16reassembly_lifetime_ms\x18\x06 \x01(\rR\x14reassemblyLifetimeMs\"\xc4\x01\n" +
	"\x0fCapabilitiesAck\x12C\n" +
	"\x1eselected_data_protocol_version\x18\x01 \x01(\rR\x1bselectedDataProtocolVersion\x122\n" +
	"\x15selected_feature_bits\x18\x02 \x01(\x04R\x13selectedFeatureBits\x128\n" +
	"\x06result\x18\x03 \x01(\x0e2 .wgf.protocol.wire.v1.ResultCodeR\x06result\"\n" +
	"\n" +
	"\bMtuProbe\"L\n" +
	"\vMtuProbeAck\x12=\n" +
	"\x1breceived_probe_payload_size\x18\x01 \x01(\rR\x18receivedProbePayloadSize\"7\n" +
	"\rResetSequence\x12&\n" +
	"\x0fdata_session_id\x18\x01 \x01(\rR\rdataSessionId\"t\n" +
	"\x10ResetSequenceAck\x12&\n" +
	"\x0fdata_session_id\x18\x01 \x01(\rR\rdataSessionId\x128\n" +
	"\x06result\x18\x02 \x01(\x0e2 .wgf.protocol.wire.v1.ResultCodeR\x06result\"&\n" +
	"\aPeerMTU\x12\x1b\n" +
	"\tinner_mtu\x18\x01 \x01(\rR\binnerMtu\"c\n" +
	"\n" +
	"PeerMTUAck\x12\x1b\n" +
	"\tinner_mtu\x18\x01 \x01(\rR\binnerMtu\x128\n" +
	"\x06result\x18\x02 \x01(\x0e2 .wgf.protocol.wire.v1.ResultCodeR\x06result\"\"\n" +
	"\x04Ping\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\rR\bsequence\"\"\n" +
	"\x04Pong\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\rR\bsequence\"\xd7\x01\n" +
	"\x11StateSyncRequired\x12F\n" +
	"\x06reason\x18\x01 \x01(\x0e2..wgf.protocol.wire.v1.StateSyncRequired.ReasonR\x06reason\x127\n" +
	"\x18observed_data_session_id\x18\x02 \x01(\rR\x15observedDataSessionId\"A\n" +
	"\x06Reason\x12\x16\n" +
	"\x12REASON_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bREASON_UNKNOWN_DATA_SESSION\x10\x01*\xd9\x01\n" +
	"\n" +
	"ResultCode\x12\x1b\n" +
	"\x17RESULT_CODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14RESULT_CODE_ACCEPTED\x10\x01\x12$\n" +
	" RESULT_CODE_INCOMPATIBLE_VERSION\x10\x02\x12(\n" +
	"$RESULT_CODE_MISSING_REQUIRED_FEATURE\x10\x03\x12!\n" +
	"\x1dRESULT_CODE_INVALID_PARAMETER\x10\x04\x12!\n" +
	"\x1dRESULT_CODE_SESSION_COLLISION\x10\x05B5Z3github.com/kurochan/wg-frag-go/proto/wire/v1;wirev1b\beditionsp\xe9\a"

var file_wire_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_wire_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_wire_v1_control_proto_goTypes = []any{
	(ResultCode)(0),               // 0: wgf.protocol.wire.v1.ResultCode
	(StateSyncRequired_Reason)(0), // 1: wgf.protocol.wire.v1.StateSyncRequired.Reason
	(*Control)(nil),               // 2: wgf.protocol.wire.v1.Control
	(*CapabilitiesHello)(nil),     // 3: wgf.protocol.wire.v1.CapabilitiesHello
	(*CapabilitiesAck)(nil),       // 4: wgf.protocol.wire.v1.CapabilitiesAck
	(*MtuProbe)(nil),              // 5: wgf.protocol.wire.v1.MtuProbe
	(*MtuProbeAck)(nil),           // 6: wgf.protocol.wire.v1.MtuProbeAck
	(*ResetSequence)(nil),         // 7: wgf.protocol.wire.v1.ResetSequence
	(*ResetSequenceAck)(nil),      // 8: wgf.protocol.wire.v1.ResetSequenceAck
	(*PeerMTU)(nil),               // 9: wgf.protocol.wire.v1.PeerMTU
	(*PeerMTUAck)(nil),            // 10: wgf.protocol.wire.v1.PeerMTUAck
	(*Ping)(nil),                  // 11: wgf.protocol.wire.v1.Ping
	(*Pong)(nil),                  // 12: wgf.protocol.wire.v1.Pong
	(*StateSyncRequired)(nil),     // 13: wgf.protocol.wire.v1.StateSyncRequired
}
var file_wire_v1_control_proto_depIdxs = []int32{
	3,  // 0: wgf.protocol.wire.v1.Control.capabilities_hello:type_name -> wgf.protocol.wire.v1.CapabilitiesHello
	5,  // 1: wgf.protocol.wire.v1.Control.mtu_probe:type_name -> wgf.protocol.wire.v1.MtuProbe
	6,  // 2: wgf.protocol.wire.v1.Control.mtu_probe_ack:type_name -> wgf.protocol.wire.v1.MtuProbeAck
	11, // 3: wgf.protocol.wire.v1.Control.ping:type_name -> wgf.protocol.wire.v1.Ping
	12, // 4: wgf.protocol.wire.v1.Control.pong:type_name -> wgf.protocol.wire.v1.Pong
	4,  // 5: wgf.protocol.wire.v1.Control.capabilities_ack:type_name -> wgf.protocol.wire.v1.CapabilitiesAck
	7,  // 6: wgf.protocol.wire.v1.Control.reset_sequence:type_name -> wgf.protocol.wire.v1.ResetSequence
	8,  // 7: wgf.protocol.wire.v1.Control.reset_sequence_ack:type_name -> wgf.protocol.wire.v1.ResetSequenceAck
	9,  // 8: wgf.protocol.wire.v1.Control.peer_mtu:type_name -> wgf.protocol.wire.v1.PeerMTU
	10, // 9: wgf.protocol.wire.v1.Control.peer_mtu_ack:type_name -> wgf.protocol.wire.v1.PeerMTUAck
	13, // 10: wgf.protocol.wire.v1.Control.state_sync_required:type_name -> wgf.protocol.wire.v1.StateSyncRequired
	0,  // 11: wgf.protocol.wire.v1.CapabilitiesAck.result:type_name -> wgf.protocol.wire.v1.ResultCode
	0,  // 12: wgf.protocol.wire.v1.ResetSequenceAck.result:type_name -> wgf.protocol.wire.v1.ResultCode
	0,  // 13: wgf.protocol.wire.v1.PeerMTUAck.result:type_name -> wgf.protocol.wire.v1.ResultCode
	1,  // 14: wgf.protocol.wire.v1.StateSyncRequired.reason:type_name -> wgf.protocol.wire.v1.StateSyncRequired.Reason
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_wire_v1_control_proto_init() }
func file_wire_v1_control_proto_init() {
	if File_wire_v1_control_proto != nil {
		return
	}
	file_wire_v1_control_proto_msgTypes[0].OneofWrappers = []any{
		(*control_CapabilitiesHello)(nil),
		(*control_MtuProbe)(nil),
		(*control_MtuProbeAck)(nil),
		(*control_Ping)(nil),
		(*control_Pong)(nil),
		(*control_CapabilitiesAck)(nil),
		(*control_ResetSequence)(nil),
		(*control_ResetSequenceAck)(nil),
		(*control_PeerMtu)(nil),
		(*control_PeerMtuAck)(nil),
		(*control_StateSyncRequired)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_v1_control_proto_rawDesc), len(file_wire_v1_control_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_v1_control_proto_goTypes,
		DependencyIndexes: file_wire_v1_control_proto_depIdxs,
		EnumInfos:         file_wire_v1_control_proto_enumTypes,
		MessageInfos:      file_wire_v1_control_proto_msgTypes,
	}.Build()
	File_wire_v1_control_proto = out.File
	file_wire_v1_control_proto_goTypes = nil
	file_wire_v1_control_proto_depIdxs = nil
}
