// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: controlapi/v1/common.proto

package controlapiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InterfaceLifecycle describes the state of an interface supervisor.
type InterfaceLifecycle int32

const (
	InterfaceLifecycle_INTERFACE_LIFECYCLE_UNSPECIFIED  InterfaceLifecycle = 0
	InterfaceLifecycle_INTERFACE_LIFECYCLE_CREATING     InterfaceLifecycle = 1
	InterfaceLifecycle_INTERFACE_LIFECYCLE_RUNNING      InterfaceLifecycle = 2
	InterfaceLifecycle_INTERFACE_LIFECYCLE_RESTARTING   InterfaceLifecycle = 3
	InterfaceLifecycle_INTERFACE_LIFECYCLE_DELETING     InterfaceLifecycle = 4
	InterfaceLifecycle_INTERFACE_LIFECYCLE_ROLLING_BACK InterfaceLifecycle = 5
	InterfaceLifecycle_INTERFACE_LIFECYCLE_ERROR        InterfaceLifecycle = 6
)

// Enum value maps for InterfaceLifecycle.
var (
	InterfaceLifecycle_name = map[int32]string{
		0: "INTERFACE_LIFECYCLE_UNSPECIFIED",
		1: "INTERFACE_LIFECYCLE_CREATING",
		2: "INTERFACE_LIFECYCLE_RUNNING",
		3: "INTERFACE_LIFECYCLE_RESTARTING",
		4: "INTERFACE_LIFECYCLE_DELETING",
		5: "INTERFACE_LIFECYCLE_ROLLING_BACK",
		6: "INTERFACE_LIFECYCLE_ERROR",
	}
	InterfaceLifecycle_value = map[string]int32{
		"INTERFACE_LIFECYCLE_UNSPECIFIED":  0,
		"INTERFACE_LIFECYCLE_CREATING":     1,
		"INTERFACE_LIFECYCLE_RUNNING":      2,
		"INTERFACE_LIFECYCLE_RESTARTING":   3,
		"INTERFACE_LIFECYCLE_DELETING":     4,
		"INTERFACE_LIFECYCLE_ROLLING_BACK": 5,
		"INTERFACE_LIFECYCLE_ERROR":        6,
	}
)

func (x InterfaceLifecycle) Enum() *InterfaceLifecycle {
	p := new(InterfaceLifecycle)
	*p = x
	return p
}

func (x InterfaceLifecycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterfaceLifecycle) Descriptor() protoreflect.EnumDescriptor {
	return file_controlapi_v1_common_proto_enumTypes[0].Descriptor()
}

func (InterfaceLifecycle) Type() protoreflect.EnumType {
	return &file_controlapi_v1_common_proto_enumTypes[0]
}

func (x InterfaceLifecycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// InterfaceRef identifies an interface and, when present, its current
// process-local instance. The instance ID prevents a stale request from
// affecting an interface that was deleted and recreated with the same name.
type InterfaceRef struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InterfaceName       *string                `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName"`
	xxx_hidden_InterfaceInstanceId []byte                 `protobuf:"bytes,2,opt,name=interface_instance_id,json=interfaceInstanceId"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *InterfaceRef) Reset() {
	*x = InterfaceRef{}
	mi := &file_controlapi_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceRef) ProtoMessage() {}

func (x *InterfaceRef) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InterfaceRef) GetInterfaceName() string {
	if x != nil {
		if x.xxx_hidden_InterfaceName != nil {
			return *x.xxx_hidden_InterfaceName
		}
		return ""
	}
	return ""
}

func (x *InterfaceRef) GetInterfaceInstanceId() []byte {
	if x != nil {
		return x.xxx_hidden_InterfaceInstanceId
	}
	return nil
}

func (x *InterfaceRef) SetInterfaceName(v string) {
	x.xxx_hidden_InterfaceName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *InterfaceRef) SetInterfaceInstanceId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_InterfaceInstanceId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *InterfaceRef) HasInterfaceName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *InterfaceRef) HasInterfaceInstanceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *InterfaceRef) ClearInterfaceName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_InterfaceName = nil
}

func (x *InterfaceRef) ClearInterfaceInstanceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_InterfaceInstanceId = nil
}

type InterfaceRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	InterfaceName       *string
	InterfaceInstanceId []byte
}

func (b0 InterfaceRef_builder) Build() *InterfaceRef {
	m0 := &InterfaceRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.InterfaceName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_InterfaceName = b.InterfaceName
	}
	if b.InterfaceInstanceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_InterfaceInstanceId = b.InterfaceInstanceId
	}
	return m0
}

// MutationContext protects a change against an outdated interface snapshot.
type MutationContext struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ExpectedInstanceId []byte                 `protobuf:"bytes,1,opt,name=expected_instance_id,json=expectedInstanceId"`
	xxx_hidden_ExpectedGeneration uint64                 `protobuf:"varint,2,opt,name=expected_generation,json=expectedGeneration"`
	xxx_hidden_RequestId          []byte                 `protobuf:"bytes,3,opt,name=request_id,json=requestId"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *MutationContext) Reset() {
	*x = MutationContext{}
	mi := &file_controlapi_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationContext) ProtoMessage() {}

func (x *MutationContext) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MutationContext) GetExpectedInstanceId() []byte {
	if x != nil {
		return x.xxx_hidden_ExpectedInstanceId
	}
	return nil
}

func (x *MutationContext) GetExpectedGeneration() uint64 {
	if x != nil {
		return x.xxx_hidden_ExpectedGeneration
	}
	return 0
}

func (x *MutationContext) GetRequestId() []byte {
	if x != nil {
		return x.xxx_hidden_RequestId
	}
	return nil
}

func (x *MutationContext) SetExpectedInstanceId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ExpectedInstanceId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *MutationContext) SetExpectedGeneration(v uint64) {
	x.xxx_hidden_ExpectedGeneration = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *MutationContext) SetRequestId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_RequestId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *MutationContext) HasExpectedInstanceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MutationContext) HasExpectedGeneration() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MutationContext) HasRequestId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *MutationContext) ClearExpectedInstanceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ExpectedInstanceId = nil
}

func (x *MutationContext) ClearExpectedGeneration() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ExpectedGeneration = 0
}

func (x *MutationContext) ClearRequestId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_RequestId = nil
}

type MutationContext_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ExpectedInstanceId []byte
	ExpectedGeneration *uint64
	RequestId          []byte
}

func (b0 MutationContext_builder) Build() *MutationContext {
	m0 := &MutationContext{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ExpectedInstanceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_ExpectedInstanceId = b.ExpectedInstanceId
	}
	if b.ExpectedGeneration != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_ExpectedGeneration = *b.ExpectedGeneration
	}
	if b.RequestId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_RequestId = b.RequestId
	}
	return m0
}

var File_controlapi_v1_common_proto protoreflect.FileDescriptor

const file_controlapi_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1acontrolapi/v1/common.proto\x12\x11wgf.controlapi.v1\"i\n" +
	"\fInterfaceRef\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x122\n" +
	"\x15interface_instance_id\x18\x02 \x01(\fR\x13interfaceInstanceId\"\x93\x01\n" +
	"\x0fMutationContext\x120\n" +
	"\x14expected_instance_id\x18\x01 \x01(\fR\x12expectedInstanceId\x12/\n" +
	"\x13expected_generation\x18\x02 \x01(\x04R\x12expectedGeneration\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\fR\trequestId*\x87\x02\n" +
	"\x12InterfaceLifecycle\x12#\n" +
	"\x1fINTERFACE_LIFECYCLE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cINTERFACE_LIFECYCLE_CREATING\x10\x01\x12\x1f\n" +
	"\x1bINTERFACE_LIFECYCLE_RUNNING\x10\x02\x12\"\n" +
	"\x1eINTERFACE_LIFECYCLE_RESTARTING\x10\x03\x12 \n" +
	"\x1cINTERFACE_LIFECYCLE_DELETING\x10\x04\x12$\n" +
	" INTERFACE_LIFECYCLE_ROLLING_BACK\x10\x05\x12\x1d\n" +
	"\x19INTERFACE_LIFECYCLE_ERROR\x10\x06BAZ?github.com/kurochan/wg-frag-go/proto/controlapi/v1;controlapiv1b\beditionsp\xe9\a"

var file_controlapi_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controlapi_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_controlapi_v1_common_proto_goTypes = []any{
	(InterfaceLifecycle)(0), // 0: wgf.controlapi.v1.InterfaceLifecycle
	(*InterfaceRef)(nil),    // 1: wgf.controlapi.v1.InterfaceRef
	(*MutationContext)(nil), // 2: wgf.controlapi.v1.MutationContext
}
var file_controlapi_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_controlapi_v1_common_proto_init() }
func file_controlapi_v1_common_proto_init() {
	if File_controlapi_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlapi_v1_common_proto_rawDesc), len(file_controlapi_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controlapi_v1_common_proto_goTypes,
		DependencyIndexes: file_controlapi_v1_common_proto_depIdxs,
		EnumInfos:         file_controlapi_v1_common_proto_enumTypes,
		MessageInfos:      file_controlapi_v1_common_proto_msgTypes,
	}.Build()
	File_controlapi_v1_common_proto = out.File
	file_controlapi_v1_common_proto_goTypes = nil
	file_controlapi_v1_common_proto_depIdxs = nil
}
