// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: controlapi/v1/controlapi.proto

package controlapiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresharedKeyAction int32

const (
	PresharedKeyAction_PRESERVE PresharedKeyAction = 0
	PresharedKeyAction_SET      PresharedKeyAction = 1
	PresharedKeyAction_CLEAR    PresharedKeyAction = 2
)

// Enum value maps for PresharedKeyAction.
var (
	PresharedKeyAction_name = map[int32]string{
		0: "PRESERVE",
		1: "SET",
		2: "CLEAR",
	}
	PresharedKeyAction_value = map[string]int32{
		"PRESERVE": 0,
		"SET":      1,
		"CLEAR":    2,
	}
)

func (x PresharedKeyAction) Enum() *PresharedKeyAction {
	p := new(PresharedKeyAction)
	*p = x
	return p
}

func (x PresharedKeyAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PresharedKeyAction) Descriptor() protoreflect.EnumDescriptor {
	return file_controlapi_v1_controlapi_proto_enumTypes[0].Descriptor()
}

func (PresharedKeyAction) Type() protoreflect.EnumType {
	return &file_controlapi_v1_controlapi_proto_enumTypes[0]
}

func (x PresharedKeyAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type GetStatusRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_IncludeSecrets bool                   `protobuf:"varint,1,opt,name=include_secrets,json=includeSecrets"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_controlapi_v1_controlapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_controlapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetStatusRequest) GetIncludeSecrets() bool {
	if x != nil {
		return x.xxx_hidden_IncludeSecrets
	}
	return false
}

func (x *GetStatusRequest) SetIncludeSecrets(v bool) {
	x.xxx_hidden_IncludeSecrets = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetStatusRequest) HasIncludeSecrets() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetStatusRequest) ClearIncludeSecrets() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_IncludeSecrets = false
}

type GetStatusRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Only the privileged local showconf path sets this flag.
	IncludeSecrets *bool
}

func (b0 GetStatusRequest_builder) Build() *GetStatusRequest {
	m0 := &GetStatusRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.IncludeSecrets != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_IncludeSecrets = *b.IncludeSecrets
	}
	return m0
}

// ApplyConfigRequest carries the complete desired peer set. Interface
// identity (private key, listen port, MTU) cannot change at runtime; requests
// implying such a change are rejected.
type ApplyConfigRequest struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RequestId          []byte                 `protobuf:"bytes,1,opt,name=request_id,json=requestId"`
	xxx_hidden_ExpectedGeneration uint64                 `protobuf:"varint,2,opt,name=expected_generation,json=expectedGeneration"`
	xxx_hidden_Peers              *[]*DesiredPeer        `protobuf:"bytes,3,rep,name=peers"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ApplyConfigRequest) Reset() {
	*x = ApplyConfigRequest{}
	mi := &file_controlapi_v1_controlapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfigRequest) ProtoMessage() {}

func (x *ApplyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_controlapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ApplyConfigRequest) GetRequestId() []byte {
	if x != nil {
		return x.xxx_hidden_RequestId
	}
	return nil
}

func (x *ApplyConfigRequest) GetExpectedGeneration() uint64 {
	if x != nil {
		return x.xxx_hidden_ExpectedGeneration
	}
	return 0
}

func (x *ApplyConfigRequest) GetPeers() []*DesiredPeer {
	if x != nil {
		if x.xxx_hidden_Peers != nil {
			return *x.xxx_hidden_Peers
		}
	}
	return nil
}

func (x *ApplyConfigRequest) SetRequestId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_RequestId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ApplyConfigRequest) SetExpectedGeneration(v uint64) {
	x.xxx_hidden_ExpectedGeneration = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ApplyConfigRequest) SetPeers(v []*DesiredPeer) {
	x.xxx_hidden_Peers = &v
}

func (x *ApplyConfigRequest) HasRequestId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ApplyConfigRequest) HasExpectedGeneration() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ApplyConfigRequest) ClearRequestId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RequestId = nil
}

func (x *ApplyConfigRequest) ClearExpectedGeneration() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ExpectedGeneration = 0
}

type ApplyConfigRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// request_id is a client-generated nonzero 16-byte value. Retrying the same
	// id with the same snapshot returns the cached first result.
	RequestId []byte
	// expected_generation guards against concurrent writers; it must match the
	// generation reported by GetStatus.
	ExpectedGeneration *uint64
	Peers              []*DesiredPeer
}

func (b0 ApplyConfigRequest_builder) Build() *ApplyConfigRequest {
	m0 := &ApplyConfigRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RequestId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_RequestId = b.RequestId
	}
	if b.ExpectedGeneration != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_ExpectedGeneration = *b.ExpectedGeneration
	}
	x.xxx_hidden_Peers = &b.Peers
	return m0
}

type DesiredPeer struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PublicKey              *string                `protobuf:"bytes,1,opt,name=public_key,json=publicKey"`
	xxx_hidden_Endpoint               *string                `protobuf:"bytes,2,opt,name=endpoint"`
	xxx_hidden_AllowedIps             []string               `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps"`
	xxx_hidden_PersistentKeepaliveSec uint32                 `protobuf:"varint,4,opt,name=persistent_keepalive_sec,json=persistentKeepaliveSec"`
	xxx_hidden_PresharedKey           []byte                 `protobuf:"bytes,5,opt,name=preshared_key,json=presharedKey"`
	xxx_hidden_PresharedKeyAction     PresharedKeyAction     `protobuf:"varint,6,opt,name=preshared_key_action,json=presharedKeyAction,enum=wgf.controlapi.v1.PresharedKeyAction"`
	XXX_raceDetectHookData            protoimpl.RaceDetectHookData
	XXX_presence                      [1]uint32
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *DesiredPeer) Reset() {
	*x = DesiredPeer{}
	mi := &file_controlapi_v1_controlapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredPeer) ProtoMessage() {}

func (x *DesiredPeer) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_controlapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DesiredPeer) GetPublicKey() string {
	if x != nil {
		if x.xxx_hidden_PublicKey != nil {
			return *x.xxx_hidden_PublicKey
		}
		return ""
	}
	return ""
}

func (x *DesiredPeer) GetEndpoint() string {
	if x != nil {
		if x.xxx_hidden_Endpoint != nil {
			return *x.xxx_hidden_Endpoint
		}
		return ""
	}
	return ""
}

func (x *DesiredPeer) GetAllowedIps() []string {
	if x != nil {
		return x.xxx_hidden_AllowedIps
	}
	return nil
}

func (x *DesiredPeer) GetPersistentKeepaliveSec() uint32 {
	if x != nil {
		return x.xxx_hidden_PersistentKeepaliveSec
	}
	return 0
}

func (x *DesiredPeer) GetPresharedKey() []byte {
	if x != nil {
		return x.xxx_hidden_PresharedKey
	}
	return nil
}

func (x *DesiredPeer) GetPresharedKeyAction() PresharedKeyAction {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 5) {
			return x.xxx_hidden_PresharedKeyAction
		}
	}
	return PresharedKeyAction_PRESERVE
}

func (x *DesiredPeer) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *DesiredPeer) SetEndpoint(v string) {
	x.xxx_hidden_Endpoint = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *DesiredPeer) SetAllowedIps(v []string) {
	x.xxx_hidden_AllowedIps = v
}

func (x *DesiredPeer) SetPersistentKeepaliveSec(v uint32) {
	x.xxx_hidden_PersistentKeepaliveSec = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *DesiredPeer) SetPresharedKey(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_PresharedKey = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *DesiredPeer) SetPresharedKeyAction(v PresharedKeyAction) {
	x.xxx_hidden_PresharedKeyAction = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *DesiredPeer) HasPublicKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DesiredPeer) HasEndpoint() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DesiredPeer) HasPersistentKeepaliveSec() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *DesiredPeer) HasPresharedKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *DesiredPeer) HasPresharedKeyAction() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *DesiredPeer) ClearPublicKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PublicKey = nil
}

func (x *DesiredPeer) ClearEndpoint() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Endpoint = nil
}

func (x *DesiredPeer) ClearPersistentKeepaliveSec() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_PersistentKeepaliveSec = 0
}

func (x *DesiredPeer) ClearPresharedKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_PresharedKey = nil
}

func (x *DesiredPeer) ClearPresharedKeyAction() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_PresharedKeyAction = PresharedKeyAction_PRESERVE
}

type DesiredPeer_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PublicKey              *string
	Endpoint               *string
	AllowedIps             []string
	PersistentKeepaliveSec *uint32
	// Raw 32-byte key. The action controls whether an omitted key is preserved
	// or cleared during a peer-set update.
	PresharedKey       []byte
	PresharedKeyAction *PresharedKeyAction
}

func (b0 DesiredPeer_builder) Build() *DesiredPeer {
	m0 := &DesiredPeer{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PublicKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_PublicKey = b.PublicKey
	}
	if b.Endpoint != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Endpoint = b.Endpoint
	}
	x.xxx_hidden_AllowedIps = b.AllowedIps
	if b.PersistentKeepaliveSec != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_PersistentKeepaliveSec = *b.PersistentKeepaliveSec
	}
	if b.PresharedKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_PresharedKey = b.PresharedKey
	}
	if b.PresharedKeyAction != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_PresharedKeyAction = *b.PresharedKeyAction
	}
	return m0
}

type ApplyConfigResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Generation  uint64                 `protobuf:"varint,1,opt,name=generation"`
	xxx_hidden_Results     *[]*PeerResult         `protobuf:"bytes,2,rep,name=results"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ApplyConfigResponse) Reset() {
	*x = ApplyConfigResponse{}
	mi := &file_controlapi_v1_controlapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfigResponse) ProtoMessage() {}

func (x *ApplyConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_controlapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ApplyConfigResponse) GetGeneration() uint64 {
	if x != nil {
		return x.xxx_hidden_Generation
	}
	return 0
}

func (x *ApplyConfigResponse) GetResults() []*PeerResult {
	if x != nil {
		if x.xxx_hidden_Results != nil {
			return *x.xxx_hidden_Results
		}
	}
	return nil
}

func (x *ApplyConfigResponse) SetGeneration(v uint64) {
	x.xxx_hidden_Generation = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ApplyConfigResponse) SetResults(v []*PeerResult) {
	x.xxx_hidden_Results = &v
}

func (x *ApplyConfigResponse) HasGeneration() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ApplyConfigResponse) ClearGeneration() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Generation = 0
}

type ApplyConfigResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Generation *uint64
	Results    []*PeerResult
}

func (b0 ApplyConfigResponse_builder) Build() *ApplyConfigResponse {
	m0 := &ApplyConfigResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Generation != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Generation = *b.Generation
	}
	x.xxx_hidden_Results = &b.Results
	return m0
}

type PeerResult struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PublicKey   *string                `protobuf:"bytes,1,opt,name=public_key,json=publicKey"`
	xxx_hidden_Error       *string                `protobuf:"bytes,2,opt,name=error"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PeerResult) Reset() {
	*x = PeerResult{}
	mi := &file_controlapi_v1_controlapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerResult) ProtoMessage() {}

func (x *PeerResult) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_controlapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PeerResult) GetPublicKey() string {
	if x != nil {
		if x.xxx_hidden_PublicKey != nil {
			return *x.xxx_hidden_PublicKey
		}
		return ""
	}
	return ""
}

func (x *PeerResult) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *PeerResult) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *PeerResult) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *PeerResult) HasPublicKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PeerResult) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PeerResult) ClearPublicKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PublicKey = nil
}

func (x *PeerResult) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Error = nil
}

type PeerResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PublicKey *string
	// error is empty on success. A failed peer stays fail-closed rather than
	// reverting to its previous state.
	Error *string
}

func (b0 PeerResult_builder) Build() *PeerResult {
	m0 := &PeerResult{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PublicKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_PublicKey = b.PublicKey
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Error = b.Error
	}
	return m0
}

type GetStatusResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InterfaceName *string                `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName"`
	xxx_hidden_PublicKey     *string                `protobuf:"bytes,2,opt,name=public_key,json=publicKey"`
	xxx_hidden_ListenPort    uint32                 `protobuf:"varint,3,opt,name=listen_port,json=listenPort"`
	xxx_hidden_Mtu           uint32                 `protobuf:"varint,4,opt,name=mtu"`
	xxx_hidden_Counters      *ShimCounters          `protobuf:"bytes,6,opt,name=counters"`
	xxx_hidden_Peers         *[]*PeerStatus         `protobuf:"bytes,7,rep,name=peers"`
	xxx_hidden_Generation    uint64                 `protobuf:"varint,9,opt,name=generation"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_controlapi_v1_controlapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_controlapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetStatusResponse) GetInterfaceName() string {
	if x != nil {
		if x.xxx_hidden_InterfaceName != nil {
			return *x.xxx_hidden_InterfaceName
		}
		return ""
	}
	return ""
}

func (x *GetStatusResponse) GetPublicKey() string {
	if x != nil {
		if x.xxx_hidden_PublicKey != nil {
			return *x.xxx_hidden_PublicKey
		}
		return ""
	}
	return ""
}

func (x *GetStatusResponse) GetListenPort() uint32 {
	if x != nil {
		return x.xxx_hidden_ListenPort
	}
	return 0
}

func (x *GetStatusResponse) GetMtu() uint32 {
	if x != nil {
		return x.xxx_hidden_Mtu
	}
	return 0
}

func (x *GetStatusResponse) GetCounters() *ShimCounters {
	if x != nil {
		return x.xxx_hidden_Counters
	}
	return nil
}

func (x *GetStatusResponse) GetPeers() []*PeerStatus {
	if x != nil {
		if x.xxx_hidden_Peers != nil {
			return *x.xxx_hidden_Peers
		}
	}
	return nil
}

func (x *GetStatusResponse) GetGeneration() uint64 {
	if x != nil {
		return x.xxx_hidden_Generation
	}
	return 0
}

func (x *GetStatusResponse) SetInterfaceName(v string) {
	x.xxx_hidden_InterfaceName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *GetStatusResponse) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *GetStatusResponse) SetListenPort(v uint32) {
	x.xxx_hidden_ListenPort = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *GetStatusResponse) SetMtu(v uint32) {
	x.xxx_hidden_Mtu = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *GetStatusResponse) SetCounters(v *ShimCounters) {
	x.xxx_hidden_Counters = v
}

func (x *GetStatusResponse) SetPeers(v []*PeerStatus) {
	x.xxx_hidden_Peers = &v
}

func (x *GetStatusResponse) SetGeneration(v uint64) {
	x.xxx_hidden_Generation = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *GetStatusResponse) HasInterfaceName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetStatusResponse) HasPublicKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetStatusResponse) HasListenPort() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetStatusResponse) HasMtu() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *GetStatusResponse) HasCounters() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Counters != nil
}

func (x *GetStatusResponse) HasGeneration() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *GetStatusResponse) ClearInterfaceName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_InterfaceName = nil
}

func (x *GetStatusResponse) ClearPublicKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PublicKey = nil
}

func (x *GetStatusResponse) ClearListenPort() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ListenPort = 0
}

func (x *GetStatusResponse) ClearMtu() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Mtu = 0
}

func (x *GetStatusResponse) ClearCounters() {
	x.xxx_hidden_Counters = nil
}

func (x *GetStatusResponse) ClearGeneration() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Generation = 0
}

type GetStatusResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	InterfaceName *string
	PublicKey     *string
	ListenPort    *uint32
	Mtu           *uint32
	Counters      *ShimCounters
	Peers         []*PeerStatus
	// generation increments on every applied configuration change and gates
	// ApplyConfig.expected_generation.
	Generation *uint64
}

func (b0 GetStatusResponse_builder) Build() *GetStatusResponse {
	m0 := &GetStatusResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.InterfaceName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_InterfaceName = b.InterfaceName
	}
	if b.PublicKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_PublicKey = b.PublicKey
	}
	if b.ListenPort != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_ListenPort = *b.ListenPort
	}
	if b.Mtu != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Mtu = *b.Mtu
	}
	x.xxx_hidden_Counters = b.Counters
	x.xxx_hidden_Peers = &b.Peers
	if b.Generation != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_Generation = *b.Generation
	}
	return m0
}

type PeerStatus struct {
	state                              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PublicKey               *string                `protobuf:"bytes,1,opt,name=public_key,json=publicKey"`
	xxx_hidden_Endpoint                *string                `protobuf:"bytes,2,opt,name=endpoint"`
	xxx_hidden_AllowedIps              []string               `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps"`
	xxx_hidden_LastHandshakeUnix       int64                  `protobuf:"varint,4,opt,name=last_handshake_unix,json=lastHandshakeUnix"`
	xxx_hidden_TransferRxBytes         uint64                 `protobuf:"varint,5,opt,name=transfer_rx_bytes,json=transferRxBytes"`
	xxx_hidden_TransferTxBytes         uint64                 `protobuf:"varint,6,opt,name=transfer_tx_bytes,json=transferTxBytes"`
	xxx_hidden_PersistentKeepaliveSec  uint32                 `protobuf:"varint,7,opt,name=persistent_keepalive_sec,json=persistentKeepaliveSec"`
	xxx_hidden_ConfirmedCarrierPayload uint32                 `protobuf:"varint,8,opt,name=confirmed_carrier_payload,json=confirmedCarrierPayload"`
	xxx_hidden_PmtuSearching           bool                   `protobuf:"varint,9,opt,name=pmtu_searching,json=pmtuSearching"`
	xxx_hidden_DataReady               bool                   `protobuf:"varint,10,opt,name=data_ready,json=dataReady"`
	xxx_hidden_ControlPathState        *string                `protobuf:"bytes,11,opt,name=control_path_state,json=controlPathState"`
	xxx_hidden_ControlPathError        *string                `protobuf:"bytes,12,opt,name=control_path_error,json=controlPathError"`
	xxx_hidden_PresharedKey            []byte                 `protobuf:"bytes,13,opt,name=preshared_key,json=presharedKey"`
	XXX_raceDetectHookData             protoimpl.RaceDetectHookData
	XXX_presence                       [1]uint32
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *PeerStatus) Reset() {
	*x = PeerStatus{}
	mi := &file_controlapi_v1_controlapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatus) ProtoMessage() {}

func (x *PeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_controlapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PeerStatus) GetPublicKey() string {
	if x != nil {
		if x.xxx_hidden_PublicKey != nil {
			return *x.xxx_hidden_PublicKey
		}
		return ""
	}
	return ""
}

func (x *PeerStatus) GetEndpoint() string {
	if x != nil {
		if x.xxx_hidden_Endpoint != nil {
			return *x.xxx_hidden_Endpoint
		}
		return ""
	}
	return ""
}

func (x *PeerStatus) GetAllowedIps() []string {
	if x != nil {
		return x.xxx_hidden_AllowedIps
	}
	return nil
}

func (x *PeerStatus) GetLastHandshakeUnix() int64 {
	if x != nil {
		return x.xxx_hidden_LastHandshakeUnix
	}
	return 0
}

func (x *PeerStatus) GetTransferRxBytes() uint64 {
	if x != nil {
		return x.xxx_hidden_TransferRxBytes
	}
	return 0
}

func (x *PeerStatus) GetTransferTxBytes() uint64 {
	if x != nil {
		return x.xxx_hidden_TransferTxBytes
	}
	return 0
}

func (x *PeerStatus) GetPersistentKeepaliveSec() uint32 {
	if x != nil {
		return x.xxx_hidden_PersistentKeepaliveSec
	}
	return 0
}

func (x *PeerStatus) GetConfirmedCarrierPayload() uint32 {
	if x != nil {
		return x.xxx_hidden_ConfirmedCarrierPayload
	}
	return 0
}

func (x *PeerStatus) GetPmtuSearching() bool {
	if x != nil {
		return x.xxx_hidden_PmtuSearching
	}
	return false
}

func (x *PeerStatus) GetDataReady() bool {
	if x != nil {
		return x.xxx_hidden_DataReady
	}
	return false
}

func (x *PeerStatus) GetControlPathState() string {
	if x != nil {
		if x.xxx_hidden_ControlPathState != nil {
			return *x.xxx_hidden_ControlPathState
		}
		return ""
	}
	return ""
}

func (x *PeerStatus) GetControlPathError() string {
	if x != nil {
		if x.xxx_hidden_ControlPathError != nil {
			return *x.xxx_hidden_ControlPathError
		}
		return ""
	}
	return ""
}

func (x *PeerStatus) GetPresharedKey() []byte {
	if x != nil {
		return x.xxx_hidden_PresharedKey
	}
	return nil
}

func (x *PeerStatus) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 13)
}

func (x *PeerStatus) SetEndpoint(v string) {
	x.xxx_hidden_Endpoint = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 13)
}

func (x *PeerStatus) SetAllowedIps(v []string) {
	x.xxx_hidden_AllowedIps = v
}

func (x *PeerStatus) SetLastHandshakeUnix(v int64) {
	x.xxx_hidden_LastHandshakeUnix = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 13)
}

func (x *PeerStatus) SetTransferRxBytes(v uint64) {
	x.xxx_hidden_TransferRxBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 13)
}

func (x *PeerStatus) SetTransferTxBytes(v uint64) {
	x.xxx_hidden_TransferTxBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 13)
}

func (x *PeerStatus) SetPersistentKeepaliveSec(v uint32) {
	x.xxx_hidden_PersistentKeepaliveSec = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 13)
}

func (x *PeerStatus) SetConfirmedCarrierPayload(v uint32) {
	x.xxx_hidden_ConfirmedCarrierPayload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 13)
}

func (x *PeerStatus) SetPmtuSearching(v bool) {
	x.xxx_hidden_PmtuSearching = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 13)
}

func (x *PeerStatus) SetDataReady(v bool) {
	x.xxx_hidden_DataReady = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 13)
}

func (x *PeerStatus) SetControlPathState(v string) {
	x.xxx_hidden_ControlPathState = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 13)
}

func (x *PeerStatus) SetControlPathError(v string) {
	x.xxx_hidden_ControlPathError = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 13)
}

func (x *PeerStatus) SetPresharedKey(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_PresharedKey = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 13)
}

func (x *PeerStatus) HasPublicKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PeerStatus) HasEndpoint() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PeerStatus) HasLastHandshakeUnix() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *PeerStatus) HasTransferRxBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *PeerStatus) HasTransferTxBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *PeerStatus) HasPersistentKeepaliveSec() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *PeerStatus) HasConfirmedCarrierPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *PeerStatus) HasPmtuSearching() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *PeerStatus) HasDataReady() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *PeerStatus) HasControlPathState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *PeerStatus) HasControlPathError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *PeerStatus) HasPresharedKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *PeerStatus) ClearPublicKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PublicKey = nil
}

func (x *PeerStatus) ClearEndpoint() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Endpoint = nil
}

func (x *PeerStatus) ClearLastHandshakeUnix() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_LastHandshakeUnix = 0
}

func (x *PeerStatus) ClearTransferRxBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_TransferRxBytes = 0
}

func (x *PeerStatus) ClearTransferTxBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_TransferTxBytes = 0
}

func (x *PeerStatus) ClearPersistentKeepaliveSec() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_PersistentKeepaliveSec = 0
}

func (x *PeerStatus) ClearConfirmedCarrierPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_ConfirmedCarrierPayload = 0
}

func (x *PeerStatus) ClearPmtuSearching() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_PmtuSearching = false
}

func (x *PeerStatus) ClearDataReady() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_DataReady = false
}

func (x *PeerStatus) ClearControlPathState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_ControlPathState = nil
}

func (x *PeerStatus) ClearControlPathError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_ControlPathError = nil
}

func (x *PeerStatus) ClearPresharedKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_PresharedKey = nil
}

type PeerStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PublicKey              *string
	Endpoint               *string
	AllowedIps             []string
	LastHandshakeUnix      *int64
	TransferRxBytes        *uint64
	TransferTxBytes        *uint64
	PersistentKeepaliveSec *uint32
	// WGF extensions.
	ConfirmedCarrierPayload *uint32
	PmtuSearching           *bool
	// data_ready is true when every CONTROL gate has confirmed and outbound
	// DATA is enabled for this peer.
	DataReady *bool
	// Stable local CONTROL path status (for example BASE, SEARCHING,
	// SEARCH_COMPLETE, or ERROR).
	ControlPathState *string
	// Stable diagnostic reason when control_path_state is ERROR.
	ControlPathError *string
	// Present only on the owner-controlled local socket so set/showconf can
	// preserve a configured key; the normal show renderer does not print it.
	PresharedKey []byte
}

func (b0 PeerStatus_builder) Build() *PeerStatus {
	m0 := &PeerStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PublicKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 13)
		x.xxx_hidden_PublicKey = b.PublicKey
	}
	if b.Endpoint != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 13)
		x.xxx_hidden_Endpoint = b.Endpoint
	}
	x.xxx_hidden_AllowedIps = b.AllowedIps
	if b.LastHandshakeUnix != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 13)
		x.xxx_hidden_LastHandshakeUnix = *b.LastHandshakeUnix
	}
	if b.TransferRxBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 13)
		x.xxx_hidden_TransferRxBytes = *b.TransferRxBytes
	}
	if b.TransferTxBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 13)
		x.xxx_hidden_TransferTxBytes = *b.TransferTxBytes
	}
	if b.PersistentKeepaliveSec != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 13)
		x.xxx_hidden_PersistentKeepaliveSec = *b.PersistentKeepaliveSec
	}
	if b.ConfirmedCarrierPayload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 13)
		x.xxx_hidden_ConfirmedCarrierPayload = *b.ConfirmedCarrierPayload
	}
	if b.PmtuSearching != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 13)
		x.xxx_hidden_PmtuSearching = *b.PmtuSearching
	}
	if b.DataReady != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 13)
		x.xxx_hidden_DataReady = *b.DataReady
	}
	if b.ControlPathState != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 13)
		x.xxx_hidden_ControlPathState = b.ControlPathState
	}
	if b.ControlPathError != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 13)
		x.xxx_hidden_ControlPathError = b.ControlPathError
	}
	if b.PresharedKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 13)
		x.xxx_hidden_PresharedKey = b.PresharedKey
	}
	return m0
}

type ShimCounters struct {
	state                                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TxCarriers                     uint64                 `protobuf:"varint,1,opt,name=tx_carriers,json=txCarriers"`
	xxx_hidden_TxPacketDrops                  uint64                 `protobuf:"varint,2,opt,name=tx_packet_drops,json=txPacketDrops"`
	xxx_hidden_TxRouteDrops                   uint64                 `protobuf:"varint,3,opt,name=tx_route_drops,json=txRouteDrops"`
	xxx_hidden_TxPeerMtuDrops                 uint64                 `protobuf:"varint,13,opt,name=tx_peer_mtu_drops,json=txPeerMtuDrops"`
	xxx_hidden_TxPtbSent                      uint64                 `protobuf:"varint,14,opt,name=tx_ptb_sent,json=txPtbSent"`
	xxx_hidden_ControlExploratoryEvictions    uint64                 `protobuf:"varint,15,opt,name=control_exploratory_evictions,json=controlExploratoryEvictions"`
	xxx_hidden_ControlCoalesces               uint64                 `protobuf:"varint,16,opt,name=control_coalesces,json=controlCoalesces"`
	xxx_hidden_ControlRateSuppressionEpisodes uint64                 `protobuf:"varint,17,opt,name=control_rate_suppression_episodes,json=controlRateSuppressionEpisodes"`
	xxx_hidden_ControlIngressRateLimited      uint64                 `protobuf:"varint,18,opt,name=control_ingress_rate_limited,json=controlIngressRateLimited"`
	xxx_hidden_RxDataCarriers                 uint64                 `protobuf:"varint,4,opt,name=rx_data_carriers,json=rxDataCarriers"`
	xxx_hidden_RxInnerDelivered               uint64                 `protobuf:"varint,5,opt,name=rx_inner_delivered,json=rxInnerDelivered"`
	xxx_hidden_RxPacketRejects                uint64                 `protobuf:"varint,6,opt,name=rx_packet_rejects,json=rxPacketRejects"`
	xxx_hidden_RxSourceSpoofDrops             uint64                 `protobuf:"varint,7,opt,name=rx_source_spoof_drops,json=rxSourceSpoofDrops"`
	xxx_hidden_RxNativeWriteDrops             uint64                 `protobuf:"varint,8,opt,name=rx_native_write_drops,json=rxNativeWriteDrops"`
	xxx_hidden_CarrierQueueOverflows          uint64                 `protobuf:"varint,9,opt,name=carrier_queue_overflows,json=carrierQueueOverflows"`
	xxx_hidden_PreconfirmDrops                uint64                 `protobuf:"varint,10,opt,name=preconfirm_drops,json=preconfirmDrops"`
	xxx_hidden_ReassemblyExpirations          uint64                 `protobuf:"varint,11,opt,name=reassembly_expirations,json=reassemblyExpirations"`
	xxx_hidden_UdpSocketDrops                 uint64                 `protobuf:"varint,12,opt,name=udp_socket_drops,json=udpSocketDrops"`
	xxx_hidden_ControlQueueDrops              uint64                 `protobuf:"varint,19,opt,name=control_queue_drops,json=controlQueueDrops"`
	xxx_hidden_ControlMaterializationDrops    uint64                 `protobuf:"varint,20,opt,name=control_materialization_drops,json=controlMaterializationDrops"`
	XXX_raceDetectHookData                    protoimpl.RaceDetectHookData
	XXX_presence                              [1]uint32
	unknownFields                             protoimpl.UnknownFields
	sizeCache                                 protoimpl.SizeCache
}

func (x *ShimCounters) Reset() {
	*x = ShimCounters{}
	mi := &file_controlapi_v1_controlapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShimCounters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShimCounters) ProtoMessage() {}

func (x *ShimCounters) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_controlapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ShimCounters) GetTxCarriers() uint64 {
	if x != nil {
		return x.xxx_hidden_TxCarriers
	}
	return 0
}

func (x *ShimCounters) GetTxPacketDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_TxPacketDrops
	}
	return 0
}

func (x *ShimCounters) GetTxRouteDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_TxRouteDrops
	}
	return 0
}

func (x *ShimCounters) GetTxPeerMtuDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_TxPeerMtuDrops
	}
	return 0
}

func (x *ShimCounters) GetTxPtbSent() uint64 {
	if x != nil {
		return x.xxx_hidden_TxPtbSent
	}
	return 0
}

func (x *ShimCounters) GetControlExploratoryEvictions() uint64 {
	if x != nil {
		return x.xxx_hidden_ControlExploratoryEvictions
	}
	return 0
}

func (x *ShimCounters) GetControlCoalesces() uint64 {
	if x != nil {
		return x.xxx_hidden_ControlCoalesces
	}
	return 0
}

func (x *ShimCounters) GetControlRateSuppressionEpisodes() uint64 {
	if x != nil {
		return x.xxx_hidden_ControlRateSuppressionEpisodes
	}
	return 0
}

func (x *ShimCounters) GetControlIngressRateLimited() uint64 {
	if x != nil {
		return x.xxx_hidden_ControlIngressRateLimited
	}
	return 0
}

func (x *ShimCounters) GetRxDataCarriers() uint64 {
	if x != nil {
		return x.xxx_hidden_RxDataCarriers
	}
	return 0
}

func (x *ShimCounters) GetRxInnerDelivered() uint64 {
	if x != nil {
		return x.xxx_hidden_RxInnerDelivered
	}
	return 0
}

func (x *ShimCounters) GetRxPacketRejects() uint64 {
	if x != nil {
		return x.xxx_hidden_RxPacketRejects
	}
	return 0
}

func (x *ShimCounters) GetRxSourceSpoofDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_RxSourceSpoofDrops
	}
	return 0
}

func (x *ShimCounters) GetRxNativeWriteDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_RxNativeWriteDrops
	}
	return 0
}

func (x *ShimCounters) GetCarrierQueueOverflows() uint64 {
	if x != nil {
		return x.xxx_hidden_CarrierQueueOverflows
	}
	return 0
}

func (x *ShimCounters) GetPreconfirmDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_PreconfirmDrops
	}
	return 0
}

func (x *ShimCounters) GetReassemblyExpirations() uint64 {
	if x != nil {
		return x.xxx_hidden_ReassemblyExpirations
	}
	return 0
}

func (x *ShimCounters) GetUdpSocketDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_UdpSocketDrops
	}
	return 0
}

func (x *ShimCounters) GetControlQueueDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_ControlQueueDrops
	}
	return 0
}

func (x *ShimCounters) GetControlMaterializationDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_ControlMaterializationDrops
	}
	return 0
}

func (x *ShimCounters) SetTxCarriers(v uint64) {
	x.xxx_hidden_TxCarriers = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 20)
}

func (x *ShimCounters) SetTxPacketDrops(v uint64) {
	x.xxx_hidden_TxPacketDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 20)
}

func (x *ShimCounters) SetTxRouteDrops(v uint64) {
	x.xxx_hidden_TxRouteDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 20)
}

func (x *ShimCounters) SetTxPeerMtuDrops(v uint64) {
	x.xxx_hidden_TxPeerMtuDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 20)
}

func (x *ShimCounters) SetTxPtbSent(v uint64) {
	x.xxx_hidden_TxPtbSent = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 20)
}

func (x *ShimCounters) SetControlExploratoryEvictions(v uint64) {
	x.xxx_hidden_ControlExploratoryEvictions = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 20)
}

func (x *ShimCounters) SetControlCoalesces(v uint64) {
	x.xxx_hidden_ControlCoalesces = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 20)
}

func (x *ShimCounters) SetControlRateSuppressionEpisodes(v uint64) {
	x.xxx_hidden_ControlRateSuppressionEpisodes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 20)
}

func (x *ShimCounters) SetControlIngressRateLimited(v uint64) {
	x.xxx_hidden_ControlIngressRateLimited = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 20)
}

func (x *ShimCounters) SetRxDataCarriers(v uint64) {
	x.xxx_hidden_RxDataCarriers = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 20)
}

func (x *ShimCounters) SetRxInnerDelivered(v uint64) {
	x.xxx_hidden_RxInnerDelivered = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 20)
}

func (x *ShimCounters) SetRxPacketRejects(v uint64) {
	x.xxx_hidden_RxPacketRejects = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 20)
}

func (x *ShimCounters) SetRxSourceSpoofDrops(v uint64) {
	x.xxx_hidden_RxSourceSpoofDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 20)
}

func (x *ShimCounters) SetRxNativeWriteDrops(v uint64) {
	x.xxx_hidden_RxNativeWriteDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 20)
}

func (x *ShimCounters) SetCarrierQueueOverflows(v uint64) {
	x.xxx_hidden_CarrierQueueOverflows = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 14, 20)
}

func (x *ShimCounters) SetPreconfirmDrops(v uint64) {
	x.xxx_hidden_PreconfirmDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 15, 20)
}

func (x *ShimCounters) SetReassemblyExpirations(v uint64) {
	x.xxx_hidden_ReassemblyExpirations = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 16, 20)
}

func (x *ShimCounters) SetUdpSocketDrops(v uint64) {
	x.xxx_hidden_UdpSocketDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 17, 20)
}

func (x *ShimCounters) SetControlQueueDrops(v uint64) {
	x.xxx_hidden_ControlQueueDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 18, 20)
}

func (x *ShimCounters) SetControlMaterializationDrops(v uint64) {
	x.xxx_hidden_ControlMaterializationDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 19, 20)
}

func (x *ShimCounters) HasTxCarriers() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ShimCounters) HasTxPacketDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ShimCounters) HasTxRouteDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ShimCounters) HasTxPeerMtuDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ShimCounters) HasTxPtbSent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ShimCounters) HasControlExploratoryEvictions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ShimCounters) HasControlCoalesces() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *ShimCounters) HasControlRateSuppressionEpisodes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *ShimCounters) HasControlIngressRateLimited() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *ShimCounters) HasRxDataCarriers() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *ShimCounters) HasRxInnerDelivered() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *ShimCounters) HasRxPacketRejects() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *ShimCounters) HasRxSourceSpoofDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *ShimCounters) HasRxNativeWriteDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *ShimCounters) HasCarrierQueueOverflows() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 14)
}

func (x *ShimCounters) HasPreconfirmDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 15)
}

func (x *ShimCounters) HasReassemblyExpirations() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 16)
}

func (x *ShimCounters) HasUdpSocketDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 17)
}

func (x *ShimCounters) HasControlQueueDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 18)
}

func (x *ShimCounters) HasControlMaterializationDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 19)
}

func (x *ShimCounters) ClearTxCarriers() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TxCarriers = 0
}

func (x *ShimCounters) ClearTxPacketDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TxPacketDrops = 0
}

func (x *ShimCounters) ClearTxRouteDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_TxRouteDrops = 0
}

func (x *ShimCounters) ClearTxPeerMtuDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_TxPeerMtuDrops = 0
}

func (x *ShimCounters) ClearTxPtbSent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_TxPtbSent = 0
}

func (x *ShimCounters) ClearControlExploratoryEvictions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_ControlExploratoryEvictions = 0
}

func (x *ShimCounters) ClearControlCoalesces() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_ControlCoalesces = 0
}

func (x *ShimCounters) ClearControlRateSuppressionEpisodes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_ControlRateSuppressionEpisodes = 0
}

func (x *ShimCounters) ClearControlIngressRateLimited() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_ControlIngressRateLimited = 0
}

func (x *ShimCounters) ClearRxDataCarriers() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_RxDataCarriers = 0
}

func (x *ShimCounters) ClearRxInnerDelivered() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_RxInnerDelivered = 0
}

func (x *ShimCounters) ClearRxPacketRejects() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_RxPacketRejects = 0
}

func (x *ShimCounters) ClearRxSourceSpoofDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_RxSourceSpoofDrops = 0
}

func (x *ShimCounters) ClearRxNativeWriteDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_RxNativeWriteDrops = 0
}

func (x *ShimCounters) ClearCarrierQueueOverflows() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 14)
	x.xxx_hidden_CarrierQueueOverflows = 0
}

func (x *ShimCounters) ClearPreconfirmDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 15)
	x.xxx_hidden_PreconfirmDrops = 0
}

func (x *ShimCounters) ClearReassemblyExpirations() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 16)
	x.xxx_hidden_ReassemblyExpirations = 0
}

func (x *ShimCounters) ClearUdpSocketDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 17)
	x.xxx_hidden_UdpSocketDrops = 0
}

func (x *ShimCounters) ClearControlQueueDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 18)
	x.xxx_hidden_ControlQueueDrops = 0
}

func (x *ShimCounters) ClearControlMaterializationDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 19)
	x.xxx_hidden_ControlMaterializationDrops = 0
}

type ShimCounters_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TxCarriers                     *uint64
	TxPacketDrops                  *uint64
	TxRouteDrops                   *uint64
	TxPeerMtuDrops                 *uint64
	TxPtbSent                      *uint64
	ControlExploratoryEvictions    *uint64
	ControlCoalesces               *uint64
	ControlRateSuppressionEpisodes *uint64
	ControlIngressRateLimited      *uint64
	RxDataCarriers                 *uint64
	RxInnerDelivered               *uint64
	RxPacketRejects                *uint64
	RxSourceSpoofDrops             *uint64
	RxNativeWriteDrops             *uint64
	CarrierQueueOverflows          *uint64
	PreconfirmDrops                *uint64
	ReassemblyExpirations          *uint64
	UdpSocketDrops                 *uint64
	ControlQueueDrops              *uint64
	ControlMaterializationDrops    *uint64
}

func (b0 ShimCounters_builder) Build() *ShimCounters {
	m0 := &ShimCounters{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TxCarriers != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 20)
		x.xxx_hidden_TxCarriers = *b.TxCarriers
	}
	if b.TxPacketDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 20)
		x.xxx_hidden_TxPacketDrops = *b.TxPacketDrops
	}
	if b.TxRouteDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 20)
		x.xxx_hidden_TxRouteDrops = *b.TxRouteDrops
	}
	if b.TxPeerMtuDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 20)
		x.xxx_hidden_TxPeerMtuDrops = *b.TxPeerMtuDrops
	}
	if b.TxPtbSent != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 20)
		x.xxx_hidden_TxPtbSent = *b.TxPtbSent
	}
	if b.ControlExploratoryEvictions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 20)
		x.xxx_hidden_ControlExploratoryEvictions = *b.ControlExploratoryEvictions
	}
	if b.ControlCoalesces != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 20)
		x.xxx_hidden_ControlCoalesces = *b.ControlCoalesces
	}
	if b.ControlRateSuppressionEpisodes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 20)
		x.xxx_hidden_ControlRateSuppressionEpisodes = *b.ControlRateSuppressionEpisodes
	}
	if b.ControlIngressRateLimited != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 20)
		x.xxx_hidden_ControlIngressRateLimited = *b.ControlIngressRateLimited
	}
	if b.RxDataCarriers != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 20)
		x.xxx_hidden_RxDataCarriers = *b.RxDataCarriers
	}
	if b.RxInnerDelivered != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 20)
		x.xxx_hidden_RxInnerDelivered = *b.RxInnerDelivered
	}
	if b.RxPacketRejects != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 20)
		x.xxx_hidden_RxPacketRejects = *b.RxPacketRejects
	}
	if b.RxSourceSpoofDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 20)
		x.xxx_hidden_RxSourceSpoofDrops = *b.RxSourceSpoofDrops
	}
	if b.RxNativeWriteDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 20)
		x.xxx_hidden_RxNativeWriteDrops = *b.RxNativeWriteDrops
	}
	if b.CarrierQueueOverflows != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 14, 20)
		x.xxx_hidden_CarrierQueueOverflows = *b.CarrierQueueOverflows
	}
	if b.PreconfirmDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 15, 20)
		x.xxx_hidden_PreconfirmDrops = *b.PreconfirmDrops
	}
	if b.ReassemblyExpirations != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 16, 20)
		x.xxx_hidden_ReassemblyExpirations = *b.ReassemblyExpirations
	}
	if b.UdpSocketDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 17, 20)
		x.xxx_hidden_UdpSocketDrops = *b.UdpSocketDrops
	}
	if b.ControlQueueDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 18, 20)
		x.xxx_hidden_ControlQueueDrops = *b.ControlQueueDrops
	}
	if b.ControlMaterializationDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 19, 20)
		x.xxx_hidden_ControlMaterializationDrops = *b.ControlMaterializationDrops
	}
	return m0
}

var File_controlapi_v1_controlapi_proto protoreflect.FileDescriptor

const file_controlapi_v1_controlapi_proto_rawDesc = "" +
	"\n" +
	"\x1econtrolapi/v1/controlapi.proto\x12\x11wgf.controlapi.v1\";\n" +
	"\x10GetStatusRequest\x12'\n" +
	"\x0finclude_secrets\x18\x01 \x01(\bR\x0eincludeSecrets\"\x9a\x01\n" +
	"\x12ApplyConfigRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\fR\trequestId\x12/\n" +
	"\x13expected_generation\x18\x02 \x01(\x04R\x12expectedGeneration\x124\n" +
	"\x05peers\x18\x03 \x03(\v2\x1e.wgf.controlapi.v1.DesiredPeerR\x05peers\"\xa1\x02\n" +
	"\vDesiredPeer\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x03 \x03(\tR\n" +
	"allowedIps\x128\n" +
	"\x18persistent_keepalive_sec\x18\x04 \x01(\rR\x16persistentKeepaliveSec\x12#\n" +
	"\rpreshared_key\x18\x05 \x01(\fR\fpresharedKey\x12W\n" +
	"\x14preshared_key_action\x18\x06 \x01(\x0e2%.wgf.controlapi.v1.PresharedKeyActionR\x12presharedKeyAction\"n\n" +
	"\x13ApplyConfigResponse\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x127\n" +
	"\aresults\x18\x02 \x03(\v2\x1d.wgf.controlapi.v1.PeerResultR\aresults\"A\n" +
	"\n" +
	"PeerResult\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xaa\x02\n" +
	"\x11GetStatusResponse\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vlisten_port\x18\x03 \x01(\rR\n" +
	"listenPort\x12\x10\n" +
	"\x03mtu\x18\x04 \x01(\rR\x03mtu\x12;\n" +
	"\bcounters\x18\x06 \x01(\v2\x1f.wgf.controlapi.v1.ShimCountersR\bcounters\x123\n" +
	"\x05peers\x18\a \x03(\v2\x1d.wgf.controlapi.v1.PeerStatusR\x05peers\x12\x1e\n" +
	"\n" +
	"generation\x18\t \x01(\x04R\n" +
	"generationJ\x04\b\x05\x10\x06J\x04\b\b\x10\t\"\xad\x04\n" +
	"\n" +
	"PeerStatus\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x03 \x03(\tR\n" +
	"allowedIps\x12.\n" +
	"\x13last_handshake_unix\x18\x04 \x01(\x03R\x11lastHandshakeUnix\x12*\n" +
	"\x11transfer_rx_bytes\x18\x05 \x01(\x04R\x0ftransferRxBytes\x12*\n" +
	"\x11transfer_tx_bytes\x18\x06 \x01(\x04R\x0ftransferTxBytes\x128\n" +
	"\x18persistent_keepalive_sec\x18\a \x01(\rR\x16persistentKeepaliveSec\x12:\n" +
	"\x19confirmed_carrier_payload\x18\b \x01(\rR\x17confirmedCarrierPayload\x12%\n" +
	"\x0epmtu_searching\x18\t \x01(\bR\rpmtuSearching\x12\x1d\n" +
	"\n" +
	"data_ready\x18\n" +
	" \x01(\bR\tdataReady\x12,\n" +
	"\x12control_path_state\x18\v \x01(\tR\x10controlPathState\x12,\n" +
	"\x12control_path_error\x18\f \x01(\tR\x10controlPathError\x12#\n" +
	"\rpreshared_key\x18\r \x01(\fR\fpresharedKey\"\xe7\a\n" +
	"\fShimCounters\x12\x1f\n" +
	"\vtx_carriers\x18\x01 \x01(\x04R\n" +
	"txCarriers\x12&\n" +
	"\x0ftx_packet_drops\x18\x02 \x01(\x04R\rtxPacketDrops\x12$\n" +
	"\x0etx_route_drops\x18\x03 \x01(\x04R\ftxRouteDrops\x12)\n" +
	"\x11tx_peer_mtu_drops\x18\r \x01(\x04R\x0etxPeerMtuDrops\x12\x1e\n" +
	"\vtx_ptb_sent\x18\x0e \x01(\x04R\ttxPtbSent\x12B\n" +
	"\x1dcontrol_exploratory_evictions\x18\x0f \x01(\x04R\x1bcontrolExploratoryEvictions\x12+\n" +
	"\x11control_coalesces\x18\x10 \x01(\x04R\x10controlCoalesces\x12I\n" +
	"!control_rate_suppression_episodes\x18\x11 \x01(\x04R\x1econtrolRateSuppressionEpisodes\x12?\n" +
	"\x1ccontrol_ingress_rate_limited\x18\x12 \x01(\x04R\x19controlIngressRateLimited\x12(\n" +
	"\x10rx_data_carriers\x18\x04 \x01(\x04R\x0erxDataCarriers\x12,\n" +
	"\x12rx_inner_delivered\x18\x05 \x01(\x04R\x10rxInnerDelivered\x12*\n" +
	"\x11rx_packet_rejects\x18\x06 \x01(\x04R\x0frxPacketRejects\x121\n" +
	"\x15rx_source_spoof_drops\x18\a \x01(\x04R\x12rxSourceSpoofDrops\x121\n" +
	"\x15rx_native_write_drops\x18\b \x01(\x04R\x12rxNativeWriteDrops\x126\n" +
	"\x17carrier_queue_overflows\x18\t \x01(\x04R\x15carrierQueueOverflows\x12)\n" +
	"\x10preconfirm_drops\x18\n" +
	" \x01(\x04R\x0fpreconfirmDrops\x125\n" +
	"\x16reassembly_expirations\x18\v \x01(\x04R\x15reassemblyExpirations\x12(\n" +
	"\x10udp_socket_drops\x18\f \x01(\x04R\x0eudpSocketDrops\x12.\n" +
	"\x13control_queue_drops\x18\x13 \x01(\x04R\x11controlQueueDrops\x12B\n" +
	"\x1dcontrol_materialization_drops\x18\x14 \x01(\x04R\x1bcontrolMaterializationDrops*6\n" +
	"\x12PresharedKeyAction\x12\f\n" +
	"\bPRESERVE\x10\x00\x12\a\n" +
	"\x03SET\x10\x01\x12\t\n" +
	"\x05CLEAR\x10\x022\xc2\x01\n" +
	"\n" +
	"ControlAPI\x12V\n" +
	"\tGetStatus\x12#.wgf.controlapi.v1.GetStatusRequest\x1a$.wgf.controlapi.v1.GetStatusResponse\x12\\\n" +
	"\vApplyConfig\x12%.wgf.controlapi.v1.ApplyConfigRequest\x1a&.wgf.controlapi.v1.ApplyConfigResponseBAZ?github.com/kurochan/wg-frag-go/proto/controlapi/v1;controlapiv1b\beditionsp\xe9\a"

var file_controlapi_v1_controlapi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controlapi_v1_controlapi_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_controlapi_v1_controlapi_proto_goTypes = []any{
	(PresharedKeyAction)(0),     // 0: wgf.controlapi.v1.PresharedKeyAction
	(*GetStatusRequest)(nil),    // 1: wgf.controlapi.v1.GetStatusRequest
	(*ApplyConfigRequest)(nil),  // 2: wgf.controlapi.v1.ApplyConfigRequest
	(*DesiredPeer)(nil),         // 3: wgf.controlapi.v1.DesiredPeer
	(*ApplyConfigResponse)(nil), // 4: wgf.controlapi.v1.ApplyConfigResponse
	(*PeerResult)(nil),          // 5: wgf.controlapi.v1.PeerResult
	(*GetStatusResponse)(nil),   // 6: wgf.controlapi.v1.GetStatusResponse
	(*PeerStatus)(nil),          // 7: wgf.controlapi.v1.PeerStatus
	(*ShimCounters)(nil),        // 8: wgf.controlapi.v1.ShimCounters
}
var file_controlapi_v1_controlapi_proto_depIdxs = []int32{
	3, // 0: wgf.controlapi.v1.ApplyConfigRequest.peers:type_name -> wgf.controlapi.v1.DesiredPeer
	0, // 1: wgf.controlapi.v1.DesiredPeer.preshared_key_action:type_name -> wgf.controlapi.v1.PresharedKeyAction
	5, // 2: wgf.controlapi.v1.ApplyConfigResponse.results:type_name -> wgf.controlapi.v1.PeerResult
	8, // 3: wgf.controlapi.v1.GetStatusResponse.counters:type_name -> wgf.controlapi.v1.ShimCounters
	7, // 4: wgf.controlapi.v1.GetStatusResponse.peers:type_name -> wgf.controlapi.v1.PeerStatus
	1, // 5: wgf.controlapi.v1.ControlAPI.GetStatus:input_type -> wgf.controlapi.v1.GetStatusRequest
	2, // 6: wgf.controlapi.v1.ControlAPI.ApplyConfig:input_type -> wgf.controlapi.v1.ApplyConfigRequest
	6, // 7: wgf.controlapi.v1.ControlAPI.GetStatus:output_type -> wgf.controlapi.v1.GetStatusResponse
	4, // 8: wgf.controlapi.v1.ControlAPI.ApplyConfig:output_type -> wgf.controlapi.v1.ApplyConfigResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_controlapi_v1_controlapi_proto_init() }
func file_controlapi_v1_controlapi_proto_init() {
	if File_controlapi_v1_controlapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlapi_v1_controlapi_proto_rawDesc), len(file_controlapi_v1_controlapi_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlapi_v1_controlapi_proto_goTypes,
		DependencyIndexes: file_controlapi_v1_controlapi_proto_depIdxs,
		EnumInfos:         file_controlapi_v1_controlapi_proto_enumTypes,
		MessageInfos:      file_controlapi_v1_controlapi_proto_msgTypes,
	}.Build()
	File_controlapi_v1_controlapi_proto = out.File
	file_controlapi_v1_controlapi_proto_goTypes = nil
	file_controlapi_v1_controlapi_proto_depIdxs = nil
}
