// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: controlapi/v1/controlapi.proto

package controlapiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlAPI_GetStatus_FullMethodName   = "/wgf.controlapi.v1.ControlAPI/GetStatus"
	ControlAPI_ApplyConfig_FullMethodName = "/wgf.controlapi.v1.ControlAPI/ApplyConfig"
)

// ControlAPIClient is the client API for ControlAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlAPI is the local per-interface management API served on a private
// Unix domain socket. It exposes only user-facing state: hidden carrier
// addresses and wireguard-go internals never appear here.
type ControlAPIClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	ApplyConfig(ctx context.Context, in *ApplyConfigRequest, opts ...grpc.CallOption) (*ApplyConfigResponse, error)
}

type controlAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewControlAPIClient(cc grpc.ClientConnInterface) ControlAPIClient {
	return &controlAPIClient{cc}
}

func (c *controlAPIClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, ControlAPI_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlAPIClient) ApplyConfig(ctx context.Context, in *ApplyConfigRequest, opts ...grpc.CallOption) (*ApplyConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyConfigResponse)
	err := c.cc.Invoke(ctx, ControlAPI_ApplyConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlAPIServer is the server API for ControlAPI service.
// All implementations must embed UnimplementedControlAPIServer
// for forward compatibility.
//
// ControlAPI is the local per-interface management API served on a private
// Unix domain socket. It exposes only user-facing state: hidden carrier
// addresses and wireguard-go internals never appear here.
type ControlAPIServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	ApplyConfig(context.Context, *ApplyConfigRequest) (*ApplyConfigResponse, error)
	mustEmbedUnimplementedControlAPIServer()
}

// UnimplementedControlAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlAPIServer struct{}

func (UnimplementedControlAPIServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedControlAPIServer) ApplyConfig(context.Context, *ApplyConfigRequest) (*ApplyConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyConfig not implemented")
}
func (UnimplementedControlAPIServer) mustEmbedUnimplementedControlAPIServer() {}
func (UnimplementedControlAPIServer) testEmbeddedByValue()                    {}

// UnsafeControlAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlAPIServer will
// result in compilation errors.
type UnsafeControlAPIServer interface {
	mustEmbedUnimplementedControlAPIServer()
}

func RegisterControlAPIServer(s grpc.ServiceRegistrar, srv ControlAPIServer) {
	// If the following call panics, it indicates UnimplementedControlAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlAPI_ServiceDesc, srv)
}

func _ControlAPI_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlAPIServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlAPI_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlAPIServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlAPI_ApplyConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlAPIServer).ApplyConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlAPI_ApplyConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlAPIServer).ApplyConfig(ctx, req.(*ApplyConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlAPI_ServiceDesc is the grpc.ServiceDesc for ControlAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wgf.controlapi.v1.ControlAPI",
	HandlerType: (*ControlAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _ControlAPI_GetStatus_Handler,
		},
		{
			MethodName: "ApplyConfig",
			Handler:    _ControlAPI_ApplyConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controlapi/v1/controlapi.proto",
}
