// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: controlapi/v1/control.proto

package controlapiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListInterfacesRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterfacesRequest) Reset() {
	*x = ListInterfacesRequest{}
	mi := &file_controlapi_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterfacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterfacesRequest) ProtoMessage() {}

func (x *ListInterfacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListInterfacesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListInterfacesRequest_builder) Build() *ListInterfacesRequest {
	m0 := &ListInterfacesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListInterfacesResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Interfaces *[]*InterfaceStatus    `protobuf:"bytes,1,rep,name=interfaces"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ListInterfacesResponse) Reset() {
	*x = ListInterfacesResponse{}
	mi := &file_controlapi_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterfacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterfacesResponse) ProtoMessage() {}

func (x *ListInterfacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListInterfacesResponse) GetInterfaces() []*InterfaceStatus {
	if x != nil {
		if x.xxx_hidden_Interfaces != nil {
			return *x.xxx_hidden_Interfaces
		}
	}
	return nil
}

func (x *ListInterfacesResponse) SetInterfaces(v []*InterfaceStatus) {
	x.xxx_hidden_Interfaces = &v
}

type ListInterfacesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Interfaces []*InterfaceStatus
}

func (b0 ListInterfacesResponse_builder) Build() *ListInterfacesResponse {
	m0 := &ListInterfacesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Interfaces = &b.Interfaces
	return m0
}

type GetInterfaceRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Target         *InterfaceRef          `protobuf:"bytes,1,opt,name=target"`
	xxx_hidden_IncludeSecrets bool                   `protobuf:"varint,2,opt,name=include_secrets,json=includeSecrets"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GetInterfaceRequest) Reset() {
	*x = GetInterfaceRequest{}
	mi := &file_controlapi_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterfaceRequest) ProtoMessage() {}

func (x *GetInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetInterfaceRequest) GetTarget() *InterfaceRef {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return nil
}

func (x *GetInterfaceRequest) GetIncludeSecrets() bool {
	if x != nil {
		return x.xxx_hidden_IncludeSecrets
	}
	return false
}

func (x *GetInterfaceRequest) SetTarget(v *InterfaceRef) {
	x.xxx_hidden_Target = v
}

func (x *GetInterfaceRequest) SetIncludeSecrets(v bool) {
	x.xxx_hidden_IncludeSecrets = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *GetInterfaceRequest) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Target != nil
}

func (x *GetInterfaceRequest) HasIncludeSecrets() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetInterfaceRequest) ClearTarget() {
	x.xxx_hidden_Target = nil
}

func (x *GetInterfaceRequest) ClearIncludeSecrets() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_IncludeSecrets = false
}

type GetInterfaceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Target *InterfaceRef
	// Enables sensitive peer fields such as preshared keys for the owner-only
	// configuration path. Private keys are never returned by this API.
	IncludeSecrets *bool
}

func (b0 GetInterfaceRequest_builder) Build() *GetInterfaceRequest {
	m0 := &GetInterfaceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Target = b.Target
	if b.IncludeSecrets != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_IncludeSecrets = *b.IncludeSecrets
	}
	return m0
}

type GetInterfaceResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status *InterfaceStatus       `protobuf:"bytes,1,opt,name=status"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetInterfaceResponse) Reset() {
	*x = GetInterfaceResponse{}
	mi := &file_controlapi_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInterfaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterfaceResponse) ProtoMessage() {}

func (x *GetInterfaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetInterfaceResponse) GetStatus() *InterfaceStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *GetInterfaceResponse) SetStatus(v *InterfaceStatus) {
	x.xxx_hidden_Status = v
}

func (x *GetInterfaceResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *GetInterfaceResponse) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type GetInterfaceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status *InterfaceStatus
}

func (b0 GetInterfaceResponse_builder) Build() *GetInterfaceResponse {
	m0 := &GetInterfaceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Status = b.Status
	return m0
}

type CreateInterfaceRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RequestId   []byte                 `protobuf:"bytes,1,opt,name=request_id,json=requestId"`
	xxx_hidden_Spec        *InterfaceSpec         `protobuf:"bytes,2,opt,name=spec"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateInterfaceRequest) Reset() {
	*x = CreateInterfaceRequest{}
	mi := &file_controlapi_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInterfaceRequest) ProtoMessage() {}

func (x *CreateInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateInterfaceRequest) GetRequestId() []byte {
	if x != nil {
		return x.xxx_hidden_RequestId
	}
	return nil
}

func (x *CreateInterfaceRequest) GetSpec() *InterfaceSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *CreateInterfaceRequest) SetRequestId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_RequestId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CreateInterfaceRequest) SetSpec(v *InterfaceSpec) {
	x.xxx_hidden_Spec = v
}

func (x *CreateInterfaceRequest) HasRequestId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateInterfaceRequest) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *CreateInterfaceRequest) ClearRequestId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RequestId = nil
}

func (x *CreateInterfaceRequest) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

type CreateInterfaceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RequestId []byte
	Spec      *InterfaceSpec
}

func (b0 CreateInterfaceRequest_builder) Build() *CreateInterfaceRequest {
	m0 := &CreateInterfaceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RequestId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_RequestId = b.RequestId
	}
	x.xxx_hidden_Spec = b.Spec
	return m0
}

type CreateInterfaceResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status *InterfaceStatus       `protobuf:"bytes,1,opt,name=status"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateInterfaceResponse) Reset() {
	*x = CreateInterfaceResponse{}
	mi := &file_controlapi_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInterfaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInterfaceResponse) ProtoMessage() {}

func (x *CreateInterfaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateInterfaceResponse) GetStatus() *InterfaceStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *CreateInterfaceResponse) SetStatus(v *InterfaceStatus) {
	x.xxx_hidden_Status = v
}

func (x *CreateInterfaceResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *CreateInterfaceResponse) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type CreateInterfaceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status *InterfaceStatus
}

func (b0 CreateInterfaceResponse_builder) Build() *CreateInterfaceResponse {
	m0 := &CreateInterfaceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Status = b.Status
	return m0
}

type DeleteInterfaceRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Target   *InterfaceRef          `protobuf:"bytes,1,opt,name=target"`
	xxx_hidden_Mutation *MutationContext       `protobuf:"bytes,2,opt,name=mutation"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DeleteInterfaceRequest) Reset() {
	*x = DeleteInterfaceRequest{}
	mi := &file_controlapi_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInterfaceRequest) ProtoMessage() {}

func (x *DeleteInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteInterfaceRequest) GetTarget() *InterfaceRef {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return nil
}

func (x *DeleteInterfaceRequest) GetMutation() *MutationContext {
	if x != nil {
		return x.xxx_hidden_Mutation
	}
	return nil
}

func (x *DeleteInterfaceRequest) SetTarget(v *InterfaceRef) {
	x.xxx_hidden_Target = v
}

func (x *DeleteInterfaceRequest) SetMutation(v *MutationContext) {
	x.xxx_hidden_Mutation = v
}

func (x *DeleteInterfaceRequest) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Target != nil
}

func (x *DeleteInterfaceRequest) HasMutation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Mutation != nil
}

func (x *DeleteInterfaceRequest) ClearTarget() {
	x.xxx_hidden_Target = nil
}

func (x *DeleteInterfaceRequest) ClearMutation() {
	x.xxx_hidden_Mutation = nil
}

type DeleteInterfaceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Target   *InterfaceRef
	Mutation *MutationContext
}

func (b0 DeleteInterfaceRequest_builder) Build() *DeleteInterfaceRequest {
	m0 := &DeleteInterfaceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Target = b.Target
	x.xxx_hidden_Mutation = b.Mutation
	return m0
}

type DeleteInterfaceResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInterfaceResponse) Reset() {
	*x = DeleteInterfaceResponse{}
	mi := &file_controlapi_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInterfaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInterfaceResponse) ProtoMessage() {}

func (x *DeleteInterfaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteInterfaceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteInterfaceResponse_builder) Build() *DeleteInterfaceResponse {
	m0 := &DeleteInterfaceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ApplyPeersRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Target   *InterfaceRef          `protobuf:"bytes,1,opt,name=target"`
	xxx_hidden_Mutation *MutationContext       `protobuf:"bytes,2,opt,name=mutation"`
	xxx_hidden_Peers    *[]*PeerSpec           `protobuf:"bytes,3,rep,name=peers"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ApplyPeersRequest) Reset() {
	*x = ApplyPeersRequest{}
	mi := &file_controlapi_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPeersRequest) ProtoMessage() {}

func (x *ApplyPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ApplyPeersRequest) GetTarget() *InterfaceRef {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return nil
}

func (x *ApplyPeersRequest) GetMutation() *MutationContext {
	if x != nil {
		return x.xxx_hidden_Mutation
	}
	return nil
}

func (x *ApplyPeersRequest) GetPeers() []*PeerSpec {
	if x != nil {
		if x.xxx_hidden_Peers != nil {
			return *x.xxx_hidden_Peers
		}
	}
	return nil
}

func (x *ApplyPeersRequest) SetTarget(v *InterfaceRef) {
	x.xxx_hidden_Target = v
}

func (x *ApplyPeersRequest) SetMutation(v *MutationContext) {
	x.xxx_hidden_Mutation = v
}

func (x *ApplyPeersRequest) SetPeers(v []*PeerSpec) {
	x.xxx_hidden_Peers = &v
}

func (x *ApplyPeersRequest) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Target != nil
}

func (x *ApplyPeersRequest) HasMutation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Mutation != nil
}

func (x *ApplyPeersRequest) ClearTarget() {
	x.xxx_hidden_Target = nil
}

func (x *ApplyPeersRequest) ClearMutation() {
	x.xxx_hidden_Mutation = nil
}

type ApplyPeersRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Target   *InterfaceRef
	Mutation *MutationContext
	Peers    []*PeerSpec
}

func (b0 ApplyPeersRequest_builder) Build() *ApplyPeersRequest {
	m0 := &ApplyPeersRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Target = b.Target
	x.xxx_hidden_Mutation = b.Mutation
	x.xxx_hidden_Peers = &b.Peers
	return m0
}

type ApplyPeersResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Generation  uint64                 `protobuf:"varint,1,opt,name=generation"`
	xxx_hidden_Results     *[]*PeerResult         `protobuf:"bytes,2,rep,name=results"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ApplyPeersResponse) Reset() {
	*x = ApplyPeersResponse{}
	mi := &file_controlapi_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPeersResponse) ProtoMessage() {}

func (x *ApplyPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ApplyPeersResponse) GetGeneration() uint64 {
	if x != nil {
		return x.xxx_hidden_Generation
	}
	return 0
}

func (x *ApplyPeersResponse) GetResults() []*PeerResult {
	if x != nil {
		if x.xxx_hidden_Results != nil {
			return *x.xxx_hidden_Results
		}
	}
	return nil
}

func (x *ApplyPeersResponse) SetGeneration(v uint64) {
	x.xxx_hidden_Generation = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ApplyPeersResponse) SetResults(v []*PeerResult) {
	x.xxx_hidden_Results = &v
}

func (x *ApplyPeersResponse) HasGeneration() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ApplyPeersResponse) ClearGeneration() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Generation = 0
}

type ApplyPeersResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Generation *uint64
	Results    []*PeerResult
}

func (b0 ApplyPeersResponse_builder) Build() *ApplyPeersResponse {
	m0 := &ApplyPeersResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Generation != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Generation = *b.Generation
	}
	x.xxx_hidden_Results = &b.Results
	return m0
}

type RestartInterfaceRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Target   *InterfaceRef          `protobuf:"bytes,1,opt,name=target"`
	xxx_hidden_Mutation *MutationContext       `protobuf:"bytes,2,opt,name=mutation"`
	xxx_hidden_Spec     *InterfaceSpec         `protobuf:"bytes,3,opt,name=spec"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RestartInterfaceRequest) Reset() {
	*x = RestartInterfaceRequest{}
	mi := &file_controlapi_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartInterfaceRequest) ProtoMessage() {}

func (x *RestartInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RestartInterfaceRequest) GetTarget() *InterfaceRef {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return nil
}

func (x *RestartInterfaceRequest) GetMutation() *MutationContext {
	if x != nil {
		return x.xxx_hidden_Mutation
	}
	return nil
}

func (x *RestartInterfaceRequest) GetSpec() *InterfaceSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *RestartInterfaceRequest) SetTarget(v *InterfaceRef) {
	x.xxx_hidden_Target = v
}

func (x *RestartInterfaceRequest) SetMutation(v *MutationContext) {
	x.xxx_hidden_Mutation = v
}

func (x *RestartInterfaceRequest) SetSpec(v *InterfaceSpec) {
	x.xxx_hidden_Spec = v
}

func (x *RestartInterfaceRequest) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Target != nil
}

func (x *RestartInterfaceRequest) HasMutation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Mutation != nil
}

func (x *RestartInterfaceRequest) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *RestartInterfaceRequest) ClearTarget() {
	x.xxx_hidden_Target = nil
}

func (x *RestartInterfaceRequest) ClearMutation() {
	x.xxx_hidden_Mutation = nil
}

func (x *RestartInterfaceRequest) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

type RestartInterfaceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Target   *InterfaceRef
	Mutation *MutationContext
	Spec     *InterfaceSpec
}

func (b0 RestartInterfaceRequest_builder) Build() *RestartInterfaceRequest {
	m0 := &RestartInterfaceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Target = b.Target
	x.xxx_hidden_Mutation = b.Mutation
	x.xxx_hidden_Spec = b.Spec
	return m0
}

type RestartInterfaceResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status *InterfaceStatus       `protobuf:"bytes,1,opt,name=status"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RestartInterfaceResponse) Reset() {
	*x = RestartInterfaceResponse{}
	mi := &file_controlapi_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartInterfaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartInterfaceResponse) ProtoMessage() {}

func (x *RestartInterfaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RestartInterfaceResponse) GetStatus() *InterfaceStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *RestartInterfaceResponse) SetStatus(v *InterfaceStatus) {
	x.xxx_hidden_Status = v
}

func (x *RestartInterfaceResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *RestartInterfaceResponse) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type RestartInterfaceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status *InterfaceStatus
}

func (b0 RestartInterfaceResponse_builder) Build() *RestartInterfaceResponse {
	m0 := &RestartInterfaceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Status = b.Status
	return m0
}

type PeerResult struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PublicKey   *string                `protobuf:"bytes,1,opt,name=public_key,json=publicKey"`
	xxx_hidden_Error       *string                `protobuf:"bytes,2,opt,name=error"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PeerResult) Reset() {
	*x = PeerResult{}
	mi := &file_controlapi_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerResult) ProtoMessage() {}

func (x *PeerResult) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PeerResult) GetPublicKey() string {
	if x != nil {
		if x.xxx_hidden_PublicKey != nil {
			return *x.xxx_hidden_PublicKey
		}
		return ""
	}
	return ""
}

func (x *PeerResult) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *PeerResult) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *PeerResult) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *PeerResult) HasPublicKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PeerResult) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PeerResult) ClearPublicKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PublicKey = nil
}

func (x *PeerResult) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Error = nil
}

type PeerResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PublicKey *string
	Error     *string
}

func (b0 PeerResult_builder) Build() *PeerResult {
	m0 := &PeerResult{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PublicKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_PublicKey = b.PublicKey
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Error = b.Error
	}
	return m0
}

var File_controlapi_v1_control_proto protoreflect.FileDescriptor

const file_controlapi_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x1bcontrolapi/v1/control.proto\x12\x11wgf.controlapi.v1\x1a\x1acontrolapi/v1/common.proto\x1a\x1dcontrolapi/v1/interface.proto\"\x17\n" +
	"\x15ListInterfacesRequest\"\\\n" +
	"\x16ListInterfacesResponse\x12B\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2\".wgf.controlapi.v1.InterfaceStatusR\n" +
	"interfaces\"w\n" +
	"\x13GetInterfaceRequest\x127\n" +
	"\x06target\x18\x01 \x01(\v2\x1f.wgf.controlapi.v1.InterfaceRefR\x06target\x12'\n" +
	"\x0finclude_secrets\x18\x02 \x01(\bR\x0eincludeSecrets\"R\n" +
	"\x14GetInterfaceResponse\x12:\n" +
	"\x06status\x18\x01 \x01(\v2\".wgf.controlapi.v1.InterfaceStatusR\x06status\"m\n" +
	"\x16CreateInterfaceRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\fR\trequestId\x124\n" +
	"\x04spec\x18\x02 \x01(\v2 .wgf.controlapi.v1.InterfaceSpecR\x04spec\"U\n" +
	"\x17CreateInterfaceResponse\x12:\n" +
	"\x06status\x18\x01 \x01(\v2\".wgf.controlapi.v1.InterfaceStatusR\x06status\"\x91\x01\n" +
	"\x16DeleteInterfaceRequest\x127\n" +
	"\x06target\x18\x01 \x01(\v2\x1f.wgf.controlapi.v1.InterfaceRefR\x06target\x12>\n" +
	"\bmutation\x18\x02 \x01(\v2\".wgf.controlapi.v1.MutationContextR\bmutation\"\x19\n" +
	"\x17DeleteInterfaceResponse\"\xbf\x01\n" +
	"\x11ApplyPeersRequest\x127\n" +
	"\x06target\x18\x01 \x01(\v2\x1f.wgf.controlapi.v1.InterfaceRefR\x06target\x12>\n" +
	"\bmutation\x18\x02 \x01(\v2\".wgf.controlapi.v1.MutationContextR\bmutation\x121\n" +
	"\x05peers\x18\x03 \x03(\v2\x1b.wgf.controlapi.v1.PeerSpecR\x05peers\"m\n" +
	"\x12ApplyPeersResponse\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x127\n" +
	"\aresults\x18\x02 \x03(\v2\x1d.wgf.controlapi.v1.PeerResultR\aresults\"\xc8\x01\n" +
	"\x17RestartInterfaceRequest\x127\n" +
	"\x06target\x18\x01 \x01(\v2\x1f.wgf.controlapi.v1.InterfaceRefR\x06target\x12>\n" +
	"\bmutation\x18\x02 \x01(\v2\".wgf.controlapi.v1.MutationContextR\bmutation\x124\n" +
	"\x04spec\x18\x03 \x01(\v2 .wgf.controlapi.v1.InterfaceSpecR\x04spec\"V\n" +
	"\x18RestartInterfaceResponse\x12:\n" +
	"\x06status\x18\x01 \x01(\v2\".wgf.controlapi.v1.InterfaceStatusR\x06status\"A\n" +
	"\n" +
	"PeerResult\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xf4\x04\n" +
	"\x0eControlService\x12e\n" +
	"\x0eListInterfaces\x12(.wgf.controlapi.v1.ListInterfacesRequest\x1a).wgf.controlapi.v1.ListInterfacesResponse\x12_\n" +
	"\fGetInterface\x12&.wgf.controlapi.v1.GetInterfaceRequest\x1a'.wgf.controlapi.v1.GetInterfaceResponse\x12h\n" +
	"\x0fCreateInterface\x12).wgf.controlapi.v1.CreateInterfaceRequest\x1a*.wgf.controlapi.v1.CreateInterfaceResponse\x12h\n" +
	"\x0fDeleteInterface\x12).wgf.controlapi.v1.DeleteInterfaceRequest\x1a*.wgf.controlapi.v1.DeleteInterfaceResponse\x12Y\n" +
	"\n" +
	"ApplyPeers\x12$.wgf.controlapi.v1.ApplyPeersRequest\x1a%.wgf.controlapi.v1.ApplyPeersResponse\x12k\n" +
	"\x10RestartInterface\x12*.wgf.controlapi.v1.RestartInterfaceRequest\x1a+.wgf.controlapi.v1.RestartInterfaceResponseBAZ?github.com/kurochan/wg-frag-go/proto/controlapi/v1;controlapiv1b\beditionsp\xe9\a"

var file_controlapi_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_controlapi_v1_control_proto_goTypes = []any{
	(*ListInterfacesRequest)(nil),    // 0: wgf.controlapi.v1.ListInterfacesRequest
	(*ListInterfacesResponse)(nil),   // 1: wgf.controlapi.v1.ListInterfacesResponse
	(*GetInterfaceRequest)(nil),      // 2: wgf.controlapi.v1.GetInterfaceRequest
	(*GetInterfaceResponse)(nil),     // 3: wgf.controlapi.v1.GetInterfaceResponse
	(*CreateInterfaceRequest)(nil),   // 4: wgf.controlapi.v1.CreateInterfaceRequest
	(*CreateInterfaceResponse)(nil),  // 5: wgf.controlapi.v1.CreateInterfaceResponse
	(*DeleteInterfaceRequest)(nil),   // 6: wgf.controlapi.v1.DeleteInterfaceRequest
	(*DeleteInterfaceResponse)(nil),  // 7: wgf.controlapi.v1.DeleteInterfaceResponse
	(*ApplyPeersRequest)(nil),        // 8: wgf.controlapi.v1.ApplyPeersRequest
	(*ApplyPeersResponse)(nil),       // 9: wgf.controlapi.v1.ApplyPeersResponse
	(*RestartInterfaceRequest)(nil),  // 10: wgf.controlapi.v1.RestartInterfaceRequest
	(*RestartInterfaceResponse)(nil), // 11: wgf.controlapi.v1.RestartInterfaceResponse
	(*PeerResult)(nil),               // 12: wgf.controlapi.v1.PeerResult
	(*InterfaceStatus)(nil),          // 13: wgf.controlapi.v1.InterfaceStatus
	(*InterfaceRef)(nil),             // 14: wgf.controlapi.v1.InterfaceRef
	(*InterfaceSpec)(nil),            // 15: wgf.controlapi.v1.InterfaceSpec
	(*MutationContext)(nil),          // 16: wgf.controlapi.v1.MutationContext
	(*PeerSpec)(nil),                 // 17: wgf.controlapi.v1.PeerSpec
}
var file_controlapi_v1_control_proto_depIdxs = []int32{
	13, // 0: wgf.controlapi.v1.ListInterfacesResponse.interfaces:type_name -> wgf.controlapi.v1.InterfaceStatus
	14, // 1: wgf.controlapi.v1.GetInterfaceRequest.target:type_name -> wgf.controlapi.v1.InterfaceRef
	13, // 2: wgf.controlapi.v1.GetInterfaceResponse.status:type_name -> wgf.controlapi.v1.InterfaceStatus
	15, // 3: wgf.controlapi.v1.CreateInterfaceRequest.spec:type_name -> wgf.controlapi.v1.InterfaceSpec
	13, // 4: wgf.controlapi.v1.CreateInterfaceResponse.status:type_name -> wgf.controlapi.v1.InterfaceStatus
	14, // 5: wgf.controlapi.v1.DeleteInterfaceRequest.target:type_name -> wgf.controlapi.v1.InterfaceRef
	16, // 6: wgf.controlapi.v1.DeleteInterfaceRequest.mutation:type_name -> wgf.controlapi.v1.MutationContext
	14, // 7: wgf.controlapi.v1.ApplyPeersRequest.target:type_name -> wgf.controlapi.v1.InterfaceRef
	16, // 8: wgf.controlapi.v1.ApplyPeersRequest.mutation:type_name -> wgf.controlapi.v1.MutationContext
	17, // 9: wgf.controlapi.v1.ApplyPeersRequest.peers:type_name -> wgf.controlapi.v1.PeerSpec
	12, // 10: wgf.controlapi.v1.ApplyPeersResponse.results:type_name -> wgf.controlapi.v1.PeerResult
	14, // 11: wgf.controlapi.v1.RestartInterfaceRequest.target:type_name -> wgf.controlapi.v1.InterfaceRef
	16, // 12: wgf.controlapi.v1.RestartInterfaceRequest.mutation:type_name -> wgf.controlapi.v1.MutationContext
	15, // 13: wgf.controlapi.v1.RestartInterfaceRequest.spec:type_name -> wgf.controlapi.v1.InterfaceSpec
	13, // 14: wgf.controlapi.v1.RestartInterfaceResponse.status:type_name -> wgf.controlapi.v1.InterfaceStatus
	0,  // 15: wgf.controlapi.v1.ControlService.ListInterfaces:input_type -> wgf.controlapi.v1.ListInterfacesRequest
	2,  // 16: wgf.controlapi.v1.ControlService.GetInterface:input_type -> wgf.controlapi.v1.GetInterfaceRequest
	4,  // 17: wgf.controlapi.v1.ControlService.CreateInterface:input_type -> wgf.controlapi.v1.CreateInterfaceRequest
	6,  // 18: wgf.controlapi.v1.ControlService.DeleteInterface:input_type -> wgf.controlapi.v1.DeleteInterfaceRequest
	8,  // 19: wgf.controlapi.v1.ControlService.ApplyPeers:input_type -> wgf.controlapi.v1.ApplyPeersRequest
	10, // 20: wgf.controlapi.v1.ControlService.RestartInterface:input_type -> wgf.controlapi.v1.RestartInterfaceRequest
	1,  // 21: wgf.controlapi.v1.ControlService.ListInterfaces:output_type -> wgf.controlapi.v1.ListInterfacesResponse
	3,  // 22: wgf.controlapi.v1.ControlService.GetInterface:output_type -> wgf.controlapi.v1.GetInterfaceResponse
	5,  // 23: wgf.controlapi.v1.ControlService.CreateInterface:output_type -> wgf.controlapi.v1.CreateInterfaceResponse
	7,  // 24: wgf.controlapi.v1.ControlService.DeleteInterface:output_type -> wgf.controlapi.v1.DeleteInterfaceResponse
	9,  // 25: wgf.controlapi.v1.ControlService.ApplyPeers:output_type -> wgf.controlapi.v1.ApplyPeersResponse
	11, // 26: wgf.controlapi.v1.ControlService.RestartInterface:output_type -> wgf.controlapi.v1.RestartInterfaceResponse
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_controlapi_v1_control_proto_init() }
func file_controlapi_v1_control_proto_init() {
	if File_controlapi_v1_control_proto != nil {
		return
	}
	file_controlapi_v1_common_proto_init()
	file_controlapi_v1_interface_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlapi_v1_control_proto_rawDesc), len(file_controlapi_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlapi_v1_control_proto_goTypes,
		DependencyIndexes: file_controlapi_v1_control_proto_depIdxs,
		MessageInfos:      file_controlapi_v1_control_proto_msgTypes,
	}.Build()
	File_controlapi_v1_control_proto = out.File
	file_controlapi_v1_control_proto_goTypes = nil
	file_controlapi_v1_control_proto_depIdxs = nil
}
