// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: controlapi/v1/interface.proto

package controlapiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresharedKeyAction int32

const (
	PresharedKeyAction_PRESERVE PresharedKeyAction = 0
	PresharedKeyAction_SET      PresharedKeyAction = 1
	PresharedKeyAction_CLEAR    PresharedKeyAction = 2
)

// Enum value maps for PresharedKeyAction.
var (
	PresharedKeyAction_name = map[int32]string{
		0: "PRESERVE",
		1: "SET",
		2: "CLEAR",
	}
	PresharedKeyAction_value = map[string]int32{
		"PRESERVE": 0,
		"SET":      1,
		"CLEAR":    2,
	}
)

func (x PresharedKeyAction) Enum() *PresharedKeyAction {
	p := new(PresharedKeyAction)
	*p = x
	return p
}

func (x PresharedKeyAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PresharedKeyAction) Descriptor() protoreflect.EnumDescriptor {
	return file_controlapi_v1_interface_proto_enumTypes[0].Descriptor()
}

func (PresharedKeyAction) Type() protoreflect.EnumType {
	return &file_controlapi_v1_interface_proto_enumTypes[0]
}

func (x PresharedKeyAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// InterfaceSpec is the complete runtime configuration for one interface.
// Address and route policy are intentionally managed outside this API.
type InterfaceSpec struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InterfaceName        *string                `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName"`
	xxx_hidden_PrivateKey           []byte                 `protobuf:"bytes,2,opt,name=private_key,json=privateKey"`
	xxx_hidden_ListenPort           uint32                 `protobuf:"varint,3,opt,name=listen_port,json=listenPort"`
	xxx_hidden_Mtu                  uint32                 `protobuf:"varint,4,opt,name=mtu"`
	xxx_hidden_MtuDiscovery         *string                `protobuf:"bytes,5,opt,name=mtu_discovery,json=mtuDiscovery"`
	xxx_hidden_MinCarrierPayload    uint32                 `protobuf:"varint,6,opt,name=min_carrier_payload,json=minCarrierPayload"`
	xxx_hidden_MaxCarrierPayload    uint32                 `protobuf:"varint,7,opt,name=max_carrier_payload,json=maxCarrierPayload"`
	xxx_hidden_ReassemblySlots      uint32                 `protobuf:"varint,8,opt,name=reassembly_slots,json=reassemblySlots"`
	xxx_hidden_PeerReassemblySlots  uint32                 `protobuf:"varint,9,opt,name=peer_reassembly_slots,json=peerReassemblySlots"`
	xxx_hidden_ReassemblyLifetimeMs uint32                 `protobuf:"varint,10,opt,name=reassembly_lifetime_ms,json=reassemblyLifetimeMs"`
	xxx_hidden_Reorder              bool                   `protobuf:"varint,11,opt,name=reorder"`
	xxx_hidden_ReorderMaxDelayMs    uint32                 `protobuf:"varint,12,opt,name=reorder_max_delay_ms,json=reorderMaxDelayMs"`
	xxx_hidden_Workers              uint32                 `protobuf:"varint,13,opt,name=workers"`
	xxx_hidden_TunQueues            uint32                 `protobuf:"varint,14,opt,name=tun_queues,json=tunQueues"`
	xxx_hidden_SocketBuffer         uint32                 `protobuf:"varint,15,opt,name=socket_buffer,json=socketBuffer"`
	xxx_hidden_FwMark               uint32                 `protobuf:"varint,16,opt,name=fw_mark,json=fwMark"`
	xxx_hidden_Peers                *[]*PeerSpec           `protobuf:"bytes,17,rep,name=peers"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *InterfaceSpec) Reset() {
	*x = InterfaceSpec{}
	mi := &file_controlapi_v1_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceSpec) ProtoMessage() {}

func (x *InterfaceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InterfaceSpec) GetInterfaceName() string {
	if x != nil {
		if x.xxx_hidden_InterfaceName != nil {
			return *x.xxx_hidden_InterfaceName
		}
		return ""
	}
	return ""
}

func (x *InterfaceSpec) GetPrivateKey() []byte {
	if x != nil {
		return x.xxx_hidden_PrivateKey
	}
	return nil
}

func (x *InterfaceSpec) GetListenPort() uint32 {
	if x != nil {
		return x.xxx_hidden_ListenPort
	}
	return 0
}

func (x *InterfaceSpec) GetMtu() uint32 {
	if x != nil {
		return x.xxx_hidden_Mtu
	}
	return 0
}

func (x *InterfaceSpec) GetMtuDiscovery() string {
	if x != nil {
		if x.xxx_hidden_MtuDiscovery != nil {
			return *x.xxx_hidden_MtuDiscovery
		}
		return ""
	}
	return ""
}

func (x *InterfaceSpec) GetMinCarrierPayload() uint32 {
	if x != nil {
		return x.xxx_hidden_MinCarrierPayload
	}
	return 0
}

func (x *InterfaceSpec) GetMaxCarrierPayload() uint32 {
	if x != nil {
		return x.xxx_hidden_MaxCarrierPayload
	}
	return 0
}

func (x *InterfaceSpec) GetReassemblySlots() uint32 {
	if x != nil {
		return x.xxx_hidden_ReassemblySlots
	}
	return 0
}

func (x *InterfaceSpec) GetPeerReassemblySlots() uint32 {
	if x != nil {
		return x.xxx_hidden_PeerReassemblySlots
	}
	return 0
}

func (x *InterfaceSpec) GetReassemblyLifetimeMs() uint32 {
	if x != nil {
		return x.xxx_hidden_ReassemblyLifetimeMs
	}
	return 0
}

func (x *InterfaceSpec) GetReorder() bool {
	if x != nil {
		return x.xxx_hidden_Reorder
	}
	return false
}

func (x *InterfaceSpec) GetReorderMaxDelayMs() uint32 {
	if x != nil {
		return x.xxx_hidden_ReorderMaxDelayMs
	}
	return 0
}

func (x *InterfaceSpec) GetWorkers() uint32 {
	if x != nil {
		return x.xxx_hidden_Workers
	}
	return 0
}

func (x *InterfaceSpec) GetTunQueues() uint32 {
	if x != nil {
		return x.xxx_hidden_TunQueues
	}
	return 0
}

func (x *InterfaceSpec) GetSocketBuffer() uint32 {
	if x != nil {
		return x.xxx_hidden_SocketBuffer
	}
	return 0
}

func (x *InterfaceSpec) GetFwMark() uint32 {
	if x != nil {
		return x.xxx_hidden_FwMark
	}
	return 0
}

func (x *InterfaceSpec) GetPeers() []*PeerSpec {
	if x != nil {
		if x.xxx_hidden_Peers != nil {
			return *x.xxx_hidden_Peers
		}
	}
	return nil
}

func (x *InterfaceSpec) SetInterfaceName(v string) {
	x.xxx_hidden_InterfaceName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 17)
}

func (x *InterfaceSpec) SetPrivateKey(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_PrivateKey = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 17)
}

func (x *InterfaceSpec) SetListenPort(v uint32) {
	x.xxx_hidden_ListenPort = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 17)
}

func (x *InterfaceSpec) SetMtu(v uint32) {
	x.xxx_hidden_Mtu = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 17)
}

func (x *InterfaceSpec) SetMtuDiscovery(v string) {
	x.xxx_hidden_MtuDiscovery = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 17)
}

func (x *InterfaceSpec) SetMinCarrierPayload(v uint32) {
	x.xxx_hidden_MinCarrierPayload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 17)
}

func (x *InterfaceSpec) SetMaxCarrierPayload(v uint32) {
	x.xxx_hidden_MaxCarrierPayload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 17)
}

func (x *InterfaceSpec) SetReassemblySlots(v uint32) {
	x.xxx_hidden_ReassemblySlots = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 17)
}

func (x *InterfaceSpec) SetPeerReassemblySlots(v uint32) {
	x.xxx_hidden_PeerReassemblySlots = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 17)
}

func (x *InterfaceSpec) SetReassemblyLifetimeMs(v uint32) {
	x.xxx_hidden_ReassemblyLifetimeMs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 17)
}

func (x *InterfaceSpec) SetReorder(v bool) {
	x.xxx_hidden_Reorder = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 17)
}

func (x *InterfaceSpec) SetReorderMaxDelayMs(v uint32) {
	x.xxx_hidden_ReorderMaxDelayMs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 17)
}

func (x *InterfaceSpec) SetWorkers(v uint32) {
	x.xxx_hidden_Workers = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 17)
}

func (x *InterfaceSpec) SetTunQueues(v uint32) {
	x.xxx_hidden_TunQueues = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 17)
}

func (x *InterfaceSpec) SetSocketBuffer(v uint32) {
	x.xxx_hidden_SocketBuffer = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 14, 17)
}

func (x *InterfaceSpec) SetFwMark(v uint32) {
	x.xxx_hidden_FwMark = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 15, 17)
}

func (x *InterfaceSpec) SetPeers(v []*PeerSpec) {
	x.xxx_hidden_Peers = &v
}

func (x *InterfaceSpec) HasInterfaceName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *InterfaceSpec) HasPrivateKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *InterfaceSpec) HasListenPort() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *InterfaceSpec) HasMtu() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *InterfaceSpec) HasMtuDiscovery() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *InterfaceSpec) HasMinCarrierPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *InterfaceSpec) HasMaxCarrierPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *InterfaceSpec) HasReassemblySlots() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *InterfaceSpec) HasPeerReassemblySlots() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *InterfaceSpec) HasReassemblyLifetimeMs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *InterfaceSpec) HasReorder() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *InterfaceSpec) HasReorderMaxDelayMs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *InterfaceSpec) HasWorkers() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *InterfaceSpec) HasTunQueues() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *InterfaceSpec) HasSocketBuffer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 14)
}

func (x *InterfaceSpec) HasFwMark() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 15)
}

func (x *InterfaceSpec) ClearInterfaceName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_InterfaceName = nil
}

func (x *InterfaceSpec) ClearPrivateKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PrivateKey = nil
}

func (x *InterfaceSpec) ClearListenPort() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ListenPort = 0
}

func (x *InterfaceSpec) ClearMtu() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Mtu = 0
}

func (x *InterfaceSpec) ClearMtuDiscovery() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_MtuDiscovery = nil
}

func (x *InterfaceSpec) ClearMinCarrierPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_MinCarrierPayload = 0
}

func (x *InterfaceSpec) ClearMaxCarrierPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_MaxCarrierPayload = 0
}

func (x *InterfaceSpec) ClearReassemblySlots() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_ReassemblySlots = 0
}

func (x *InterfaceSpec) ClearPeerReassemblySlots() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_PeerReassemblySlots = 0
}

func (x *InterfaceSpec) ClearReassemblyLifetimeMs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_ReassemblyLifetimeMs = 0
}

func (x *InterfaceSpec) ClearReorder() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_Reorder = false
}

func (x *InterfaceSpec) ClearReorderMaxDelayMs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_ReorderMaxDelayMs = 0
}

func (x *InterfaceSpec) ClearWorkers() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_Workers = 0
}

func (x *InterfaceSpec) ClearTunQueues() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_TunQueues = 0
}

func (x *InterfaceSpec) ClearSocketBuffer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 14)
	x.xxx_hidden_SocketBuffer = 0
}

func (x *InterfaceSpec) ClearFwMark() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 15)
	x.xxx_hidden_FwMark = 0
}

type InterfaceSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	InterfaceName        *string
	PrivateKey           []byte
	ListenPort           *uint32
	Mtu                  *uint32
	MtuDiscovery         *string
	MinCarrierPayload    *uint32
	MaxCarrierPayload    *uint32
	ReassemblySlots      *uint32
	PeerReassemblySlots  *uint32
	ReassemblyLifetimeMs *uint32
	Reorder              *bool
	ReorderMaxDelayMs    *uint32
	Workers              *uint32
	TunQueues            *uint32
	SocketBuffer         *uint32
	FwMark               *uint32
	Peers                []*PeerSpec
}

func (b0 InterfaceSpec_builder) Build() *InterfaceSpec {
	m0 := &InterfaceSpec{}
	b, x := &b0, m0
	_, _ = b, x
	if b.InterfaceName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 17)
		x.xxx_hidden_InterfaceName = b.InterfaceName
	}
	if b.PrivateKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 17)
		x.xxx_hidden_PrivateKey = b.PrivateKey
	}
	if b.ListenPort != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 17)
		x.xxx_hidden_ListenPort = *b.ListenPort
	}
	if b.Mtu != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 17)
		x.xxx_hidden_Mtu = *b.Mtu
	}
	if b.MtuDiscovery != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 17)
		x.xxx_hidden_MtuDiscovery = b.MtuDiscovery
	}
	if b.MinCarrierPayload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 17)
		x.xxx_hidden_MinCarrierPayload = *b.MinCarrierPayload
	}
	if b.MaxCarrierPayload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 17)
		x.xxx_hidden_MaxCarrierPayload = *b.MaxCarrierPayload
	}
	if b.ReassemblySlots != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 17)
		x.xxx_hidden_ReassemblySlots = *b.ReassemblySlots
	}
	if b.PeerReassemblySlots != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 17)
		x.xxx_hidden_PeerReassemblySlots = *b.PeerReassemblySlots
	}
	if b.ReassemblyLifetimeMs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 17)
		x.xxx_hidden_ReassemblyLifetimeMs = *b.ReassemblyLifetimeMs
	}
	if b.Reorder != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 17)
		x.xxx_hidden_Reorder = *b.Reorder
	}
	if b.ReorderMaxDelayMs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 17)
		x.xxx_hidden_ReorderMaxDelayMs = *b.ReorderMaxDelayMs
	}
	if b.Workers != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 17)
		x.xxx_hidden_Workers = *b.Workers
	}
	if b.TunQueues != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 17)
		x.xxx_hidden_TunQueues = *b.TunQueues
	}
	if b.SocketBuffer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 14, 17)
		x.xxx_hidden_SocketBuffer = *b.SocketBuffer
	}
	if b.FwMark != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 15, 17)
		x.xxx_hidden_FwMark = *b.FwMark
	}
	x.xxx_hidden_Peers = &b.Peers
	return m0
}

// PeerSpec is one peer in an interface desired state.
type PeerSpec struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PublicKey              *string                `protobuf:"bytes,1,opt,name=public_key,json=publicKey"`
	xxx_hidden_Endpoint               *string                `protobuf:"bytes,2,opt,name=endpoint"`
	xxx_hidden_AllowedIps             []string               `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps"`
	xxx_hidden_PersistentKeepaliveSec uint32                 `protobuf:"varint,4,opt,name=persistent_keepalive_sec,json=persistentKeepaliveSec"`
	xxx_hidden_PresharedKey           []byte                 `protobuf:"bytes,5,opt,name=preshared_key,json=presharedKey"`
	xxx_hidden_PresharedKeyAction     PresharedKeyAction     `protobuf:"varint,6,opt,name=preshared_key_action,json=presharedKeyAction,enum=wgf.controlapi.v1.PresharedKeyAction"`
	xxx_hidden_MetricsId              *string                `protobuf:"bytes,7,opt,name=metrics_id,json=metricsId"`
	XXX_raceDetectHookData            protoimpl.RaceDetectHookData
	XXX_presence                      [1]uint32
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *PeerSpec) Reset() {
	*x = PeerSpec{}
	mi := &file_controlapi_v1_interface_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerSpec) ProtoMessage() {}

func (x *PeerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_interface_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PeerSpec) GetPublicKey() string {
	if x != nil {
		if x.xxx_hidden_PublicKey != nil {
			return *x.xxx_hidden_PublicKey
		}
		return ""
	}
	return ""
}

func (x *PeerSpec) GetEndpoint() string {
	if x != nil {
		if x.xxx_hidden_Endpoint != nil {
			return *x.xxx_hidden_Endpoint
		}
		return ""
	}
	return ""
}

func (x *PeerSpec) GetAllowedIps() []string {
	if x != nil {
		return x.xxx_hidden_AllowedIps
	}
	return nil
}

func (x *PeerSpec) GetPersistentKeepaliveSec() uint32 {
	if x != nil {
		return x.xxx_hidden_PersistentKeepaliveSec
	}
	return 0
}

func (x *PeerSpec) GetPresharedKey() []byte {
	if x != nil {
		return x.xxx_hidden_PresharedKey
	}
	return nil
}

func (x *PeerSpec) GetPresharedKeyAction() PresharedKeyAction {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 5) {
			return x.xxx_hidden_PresharedKeyAction
		}
	}
	return PresharedKeyAction_PRESERVE
}

func (x *PeerSpec) GetMetricsId() string {
	if x != nil {
		if x.xxx_hidden_MetricsId != nil {
			return *x.xxx_hidden_MetricsId
		}
		return ""
	}
	return ""
}

func (x *PeerSpec) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *PeerSpec) SetEndpoint(v string) {
	x.xxx_hidden_Endpoint = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *PeerSpec) SetAllowedIps(v []string) {
	x.xxx_hidden_AllowedIps = v
}

func (x *PeerSpec) SetPersistentKeepaliveSec(v uint32) {
	x.xxx_hidden_PersistentKeepaliveSec = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *PeerSpec) SetPresharedKey(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_PresharedKey = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *PeerSpec) SetPresharedKeyAction(v PresharedKeyAction) {
	x.xxx_hidden_PresharedKeyAction = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *PeerSpec) SetMetricsId(v string) {
	x.xxx_hidden_MetricsId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *PeerSpec) HasPublicKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PeerSpec) HasEndpoint() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PeerSpec) HasPersistentKeepaliveSec() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *PeerSpec) HasPresharedKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *PeerSpec) HasPresharedKeyAction() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *PeerSpec) HasMetricsId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *PeerSpec) ClearPublicKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PublicKey = nil
}

func (x *PeerSpec) ClearEndpoint() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Endpoint = nil
}

func (x *PeerSpec) ClearPersistentKeepaliveSec() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_PersistentKeepaliveSec = 0
}

func (x *PeerSpec) ClearPresharedKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_PresharedKey = nil
}

func (x *PeerSpec) ClearPresharedKeyAction() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_PresharedKeyAction = PresharedKeyAction_PRESERVE
}

func (x *PeerSpec) ClearMetricsId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_MetricsId = nil
}

type PeerSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PublicKey              *string
	Endpoint               *string
	AllowedIps             []string
	PersistentKeepaliveSec *uint32
	PresharedKey           []byte
	PresharedKeyAction     *PresharedKeyAction
	MetricsId              *string
}

func (b0 PeerSpec_builder) Build() *PeerSpec {
	m0 := &PeerSpec{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PublicKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_PublicKey = b.PublicKey
	}
	if b.Endpoint != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Endpoint = b.Endpoint
	}
	x.xxx_hidden_AllowedIps = b.AllowedIps
	if b.PersistentKeepaliveSec != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_PersistentKeepaliveSec = *b.PersistentKeepaliveSec
	}
	if b.PresharedKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_PresharedKey = b.PresharedKey
	}
	if b.PresharedKeyAction != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_PresharedKeyAction = *b.PresharedKeyAction
	}
	if b.MetricsId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_MetricsId = b.MetricsId
	}
	return m0
}

// InterfaceStatus is the observable state of one interface.
type InterfaceStatus struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref                 *InterfaceRef          `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Lifecycle           InterfaceLifecycle     `protobuf:"varint,2,opt,name=lifecycle,enum=wgf.controlapi.v1.InterfaceLifecycle"`
	xxx_hidden_LifecycleError      *string                `protobuf:"bytes,3,opt,name=lifecycle_error,json=lifecycleError"`
	xxx_hidden_PublicKey           *string                `protobuf:"bytes,4,opt,name=public_key,json=publicKey"`
	xxx_hidden_ListenPort          uint32                 `protobuf:"varint,5,opt,name=listen_port,json=listenPort"`
	xxx_hidden_Mtu                 uint32                 `protobuf:"varint,6,opt,name=mtu"`
	xxx_hidden_Counters            *ShimCounters          `protobuf:"bytes,7,opt,name=counters"`
	xxx_hidden_Peers               *[]*PeerStatus         `protobuf:"bytes,8,rep,name=peers"`
	xxx_hidden_Generation          uint64                 `protobuf:"varint,9,opt,name=generation"`
	xxx_hidden_Spec                *InterfaceSpec         `protobuf:"bytes,10,opt,name=spec"`
	xxx_hidden_NativeInterfaceName *string                `protobuf:"bytes,11,opt,name=native_interface_name,json=nativeInterfaceName"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *InterfaceStatus) Reset() {
	*x = InterfaceStatus{}
	mi := &file_controlapi_v1_interface_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceStatus) ProtoMessage() {}

func (x *InterfaceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_interface_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InterfaceStatus) GetRef() *InterfaceRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *InterfaceStatus) GetLifecycle() InterfaceLifecycle {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Lifecycle
		}
	}
	return InterfaceLifecycle_INTERFACE_LIFECYCLE_UNSPECIFIED
}

func (x *InterfaceStatus) GetLifecycleError() string {
	if x != nil {
		if x.xxx_hidden_LifecycleError != nil {
			return *x.xxx_hidden_LifecycleError
		}
		return ""
	}
	return ""
}

func (x *InterfaceStatus) GetPublicKey() string {
	if x != nil {
		if x.xxx_hidden_PublicKey != nil {
			return *x.xxx_hidden_PublicKey
		}
		return ""
	}
	return ""
}

func (x *InterfaceStatus) GetListenPort() uint32 {
	if x != nil {
		return x.xxx_hidden_ListenPort
	}
	return 0
}

func (x *InterfaceStatus) GetMtu() uint32 {
	if x != nil {
		return x.xxx_hidden_Mtu
	}
	return 0
}

func (x *InterfaceStatus) GetCounters() *ShimCounters {
	if x != nil {
		return x.xxx_hidden_Counters
	}
	return nil
}

func (x *InterfaceStatus) GetPeers() []*PeerStatus {
	if x != nil {
		if x.xxx_hidden_Peers != nil {
			return *x.xxx_hidden_Peers
		}
	}
	return nil
}

func (x *InterfaceStatus) GetGeneration() uint64 {
	if x != nil {
		return x.xxx_hidden_Generation
	}
	return 0
}

func (x *InterfaceStatus) GetSpec() *InterfaceSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *InterfaceStatus) GetNativeInterfaceName() string {
	if x != nil {
		if x.xxx_hidden_NativeInterfaceName != nil {
			return *x.xxx_hidden_NativeInterfaceName
		}
		return ""
	}
	return ""
}

func (x *InterfaceStatus) SetRef(v *InterfaceRef) {
	x.xxx_hidden_Ref = v
}

func (x *InterfaceStatus) SetLifecycle(v InterfaceLifecycle) {
	x.xxx_hidden_Lifecycle = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 11)
}

func (x *InterfaceStatus) SetLifecycleError(v string) {
	x.xxx_hidden_LifecycleError = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 11)
}

func (x *InterfaceStatus) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 11)
}

func (x *InterfaceStatus) SetListenPort(v uint32) {
	x.xxx_hidden_ListenPort = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 11)
}

func (x *InterfaceStatus) SetMtu(v uint32) {
	x.xxx_hidden_Mtu = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 11)
}

func (x *InterfaceStatus) SetCounters(v *ShimCounters) {
	x.xxx_hidden_Counters = v
}

func (x *InterfaceStatus) SetPeers(v []*PeerStatus) {
	x.xxx_hidden_Peers = &v
}

func (x *InterfaceStatus) SetGeneration(v uint64) {
	x.xxx_hidden_Generation = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 11)
}

func (x *InterfaceStatus) SetSpec(v *InterfaceSpec) {
	x.xxx_hidden_Spec = v
}

func (x *InterfaceStatus) SetNativeInterfaceName(v string) {
	x.xxx_hidden_NativeInterfaceName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 11)
}

func (x *InterfaceStatus) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *InterfaceStatus) HasLifecycle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *InterfaceStatus) HasLifecycleError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *InterfaceStatus) HasPublicKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *InterfaceStatus) HasListenPort() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *InterfaceStatus) HasMtu() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *InterfaceStatus) HasCounters() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Counters != nil
}

func (x *InterfaceStatus) HasGeneration() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *InterfaceStatus) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *InterfaceStatus) HasNativeInterfaceName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *InterfaceStatus) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *InterfaceStatus) ClearLifecycle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Lifecycle = InterfaceLifecycle_INTERFACE_LIFECYCLE_UNSPECIFIED
}

func (x *InterfaceStatus) ClearLifecycleError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_LifecycleError = nil
}

func (x *InterfaceStatus) ClearPublicKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_PublicKey = nil
}

func (x *InterfaceStatus) ClearListenPort() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_ListenPort = 0
}

func (x *InterfaceStatus) ClearMtu() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Mtu = 0
}

func (x *InterfaceStatus) ClearCounters() {
	x.xxx_hidden_Counters = nil
}

func (x *InterfaceStatus) ClearGeneration() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Generation = 0
}

func (x *InterfaceStatus) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *InterfaceStatus) ClearNativeInterfaceName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_NativeInterfaceName = nil
}

type InterfaceStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref            *InterfaceRef
	Lifecycle      *InterfaceLifecycle
	LifecycleError *string
	PublicKey      *string
	ListenPort     *uint32
	Mtu            *uint32
	Counters       *ShimCounters
	Peers          []*PeerStatus
	Generation     *uint64
	// spec is the current non-secret desired state. Private keys are never
	// returned; RestartInterface preserves the current private key when omitted.
	Spec *InterfaceSpec
	// native_interface_name is the OS TUN name. It can differ from the managed
	// interface name, notably when macOS allocates a utunN device.
	NativeInterfaceName *string
}

func (b0 InterfaceStatus_builder) Build() *InterfaceStatus {
	m0 := &InterfaceStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Lifecycle != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 11)
		x.xxx_hidden_Lifecycle = *b.Lifecycle
	}
	if b.LifecycleError != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 11)
		x.xxx_hidden_LifecycleError = b.LifecycleError
	}
	if b.PublicKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 11)
		x.xxx_hidden_PublicKey = b.PublicKey
	}
	if b.ListenPort != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 11)
		x.xxx_hidden_ListenPort = *b.ListenPort
	}
	if b.Mtu != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 11)
		x.xxx_hidden_Mtu = *b.Mtu
	}
	x.xxx_hidden_Counters = b.Counters
	x.xxx_hidden_Peers = &b.Peers
	if b.Generation != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 11)
		x.xxx_hidden_Generation = *b.Generation
	}
	x.xxx_hidden_Spec = b.Spec
	if b.NativeInterfaceName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 11)
		x.xxx_hidden_NativeInterfaceName = b.NativeInterfaceName
	}
	return m0
}

type PeerStatus struct {
	state                              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PublicKey               *string                `protobuf:"bytes,1,opt,name=public_key,json=publicKey"`
	xxx_hidden_Endpoint                *string                `protobuf:"bytes,2,opt,name=endpoint"`
	xxx_hidden_AllowedIps              []string               `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps"`
	xxx_hidden_LastHandshakeUnix       int64                  `protobuf:"varint,4,opt,name=last_handshake_unix,json=lastHandshakeUnix"`
	xxx_hidden_TransferRxBytes         uint64                 `protobuf:"varint,5,opt,name=transfer_rx_bytes,json=transferRxBytes"`
	xxx_hidden_TransferTxBytes         uint64                 `protobuf:"varint,6,opt,name=transfer_tx_bytes,json=transferTxBytes"`
	xxx_hidden_PersistentKeepaliveSec  uint32                 `protobuf:"varint,7,opt,name=persistent_keepalive_sec,json=persistentKeepaliveSec"`
	xxx_hidden_ConfirmedCarrierPayload uint32                 `protobuf:"varint,8,opt,name=confirmed_carrier_payload,json=confirmedCarrierPayload"`
	xxx_hidden_PmtuSearching           bool                   `protobuf:"varint,9,opt,name=pmtu_searching,json=pmtuSearching"`
	xxx_hidden_DataReady               bool                   `protobuf:"varint,10,opt,name=data_ready,json=dataReady"`
	xxx_hidden_ControlPathState        *string                `protobuf:"bytes,11,opt,name=control_path_state,json=controlPathState"`
	xxx_hidden_ControlPathError        *string                `protobuf:"bytes,12,opt,name=control_path_error,json=controlPathError"`
	xxx_hidden_PresharedKey            []byte                 `protobuf:"bytes,13,opt,name=preshared_key,json=presharedKey"`
	xxx_hidden_MetricsId               *string                `protobuf:"bytes,14,opt,name=metrics_id,json=metricsId"`
	XXX_raceDetectHookData             protoimpl.RaceDetectHookData
	XXX_presence                       [1]uint32
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *PeerStatus) Reset() {
	*x = PeerStatus{}
	mi := &file_controlapi_v1_interface_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatus) ProtoMessage() {}

func (x *PeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_interface_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PeerStatus) GetPublicKey() string {
	if x != nil {
		if x.xxx_hidden_PublicKey != nil {
			return *x.xxx_hidden_PublicKey
		}
		return ""
	}
	return ""
}

func (x *PeerStatus) GetEndpoint() string {
	if x != nil {
		if x.xxx_hidden_Endpoint != nil {
			return *x.xxx_hidden_Endpoint
		}
		return ""
	}
	return ""
}

func (x *PeerStatus) GetAllowedIps() []string {
	if x != nil {
		return x.xxx_hidden_AllowedIps
	}
	return nil
}

func (x *PeerStatus) GetLastHandshakeUnix() int64 {
	if x != nil {
		return x.xxx_hidden_LastHandshakeUnix
	}
	return 0
}

func (x *PeerStatus) GetTransferRxBytes() uint64 {
	if x != nil {
		return x.xxx_hidden_TransferRxBytes
	}
	return 0
}

func (x *PeerStatus) GetTransferTxBytes() uint64 {
	if x != nil {
		return x.xxx_hidden_TransferTxBytes
	}
	return 0
}

func (x *PeerStatus) GetPersistentKeepaliveSec() uint32 {
	if x != nil {
		return x.xxx_hidden_PersistentKeepaliveSec
	}
	return 0
}

func (x *PeerStatus) GetConfirmedCarrierPayload() uint32 {
	if x != nil {
		return x.xxx_hidden_ConfirmedCarrierPayload
	}
	return 0
}

func (x *PeerStatus) GetPmtuSearching() bool {
	if x != nil {
		return x.xxx_hidden_PmtuSearching
	}
	return false
}

func (x *PeerStatus) GetDataReady() bool {
	if x != nil {
		return x.xxx_hidden_DataReady
	}
	return false
}

func (x *PeerStatus) GetControlPathState() string {
	if x != nil {
		if x.xxx_hidden_ControlPathState != nil {
			return *x.xxx_hidden_ControlPathState
		}
		return ""
	}
	return ""
}

func (x *PeerStatus) GetControlPathError() string {
	if x != nil {
		if x.xxx_hidden_ControlPathError != nil {
			return *x.xxx_hidden_ControlPathError
		}
		return ""
	}
	return ""
}

func (x *PeerStatus) GetPresharedKey() []byte {
	if x != nil {
		return x.xxx_hidden_PresharedKey
	}
	return nil
}

func (x *PeerStatus) GetMetricsId() string {
	if x != nil {
		if x.xxx_hidden_MetricsId != nil {
			return *x.xxx_hidden_MetricsId
		}
		return ""
	}
	return ""
}

func (x *PeerStatus) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 14)
}

func (x *PeerStatus) SetEndpoint(v string) {
	x.xxx_hidden_Endpoint = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 14)
}

func (x *PeerStatus) SetAllowedIps(v []string) {
	x.xxx_hidden_AllowedIps = v
}

func (x *PeerStatus) SetLastHandshakeUnix(v int64) {
	x.xxx_hidden_LastHandshakeUnix = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 14)
}

func (x *PeerStatus) SetTransferRxBytes(v uint64) {
	x.xxx_hidden_TransferRxBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 14)
}

func (x *PeerStatus) SetTransferTxBytes(v uint64) {
	x.xxx_hidden_TransferTxBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 14)
}

func (x *PeerStatus) SetPersistentKeepaliveSec(v uint32) {
	x.xxx_hidden_PersistentKeepaliveSec = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 14)
}

func (x *PeerStatus) SetConfirmedCarrierPayload(v uint32) {
	x.xxx_hidden_ConfirmedCarrierPayload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 14)
}

func (x *PeerStatus) SetPmtuSearching(v bool) {
	x.xxx_hidden_PmtuSearching = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 14)
}

func (x *PeerStatus) SetDataReady(v bool) {
	x.xxx_hidden_DataReady = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 14)
}

func (x *PeerStatus) SetControlPathState(v string) {
	x.xxx_hidden_ControlPathState = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 14)
}

func (x *PeerStatus) SetControlPathError(v string) {
	x.xxx_hidden_ControlPathError = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 14)
}

func (x *PeerStatus) SetPresharedKey(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_PresharedKey = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 14)
}

func (x *PeerStatus) SetMetricsId(v string) {
	x.xxx_hidden_MetricsId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 14)
}

func (x *PeerStatus) HasPublicKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PeerStatus) HasEndpoint() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PeerStatus) HasLastHandshakeUnix() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *PeerStatus) HasTransferRxBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *PeerStatus) HasTransferTxBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *PeerStatus) HasPersistentKeepaliveSec() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *PeerStatus) HasConfirmedCarrierPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *PeerStatus) HasPmtuSearching() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *PeerStatus) HasDataReady() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *PeerStatus) HasControlPathState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *PeerStatus) HasControlPathError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *PeerStatus) HasPresharedKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *PeerStatus) HasMetricsId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *PeerStatus) ClearPublicKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PublicKey = nil
}

func (x *PeerStatus) ClearEndpoint() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Endpoint = nil
}

func (x *PeerStatus) ClearLastHandshakeUnix() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_LastHandshakeUnix = 0
}

func (x *PeerStatus) ClearTransferRxBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_TransferRxBytes = 0
}

func (x *PeerStatus) ClearTransferTxBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_TransferTxBytes = 0
}

func (x *PeerStatus) ClearPersistentKeepaliveSec() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_PersistentKeepaliveSec = 0
}

func (x *PeerStatus) ClearConfirmedCarrierPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_ConfirmedCarrierPayload = 0
}

func (x *PeerStatus) ClearPmtuSearching() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_PmtuSearching = false
}

func (x *PeerStatus) ClearDataReady() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_DataReady = false
}

func (x *PeerStatus) ClearControlPathState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_ControlPathState = nil
}

func (x *PeerStatus) ClearControlPathError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_ControlPathError = nil
}

func (x *PeerStatus) ClearPresharedKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_PresharedKey = nil
}

func (x *PeerStatus) ClearMetricsId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_MetricsId = nil
}

type PeerStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PublicKey               *string
	Endpoint                *string
	AllowedIps              []string
	LastHandshakeUnix       *int64
	TransferRxBytes         *uint64
	TransferTxBytes         *uint64
	PersistentKeepaliveSec  *uint32
	ConfirmedCarrierPayload *uint32
	PmtuSearching           *bool
	DataReady               *bool
	ControlPathState        *string
	ControlPathError        *string
	PresharedKey            []byte
	MetricsId               *string
}

func (b0 PeerStatus_builder) Build() *PeerStatus {
	m0 := &PeerStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PublicKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 14)
		x.xxx_hidden_PublicKey = b.PublicKey
	}
	if b.Endpoint != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 14)
		x.xxx_hidden_Endpoint = b.Endpoint
	}
	x.xxx_hidden_AllowedIps = b.AllowedIps
	if b.LastHandshakeUnix != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 14)
		x.xxx_hidden_LastHandshakeUnix = *b.LastHandshakeUnix
	}
	if b.TransferRxBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 14)
		x.xxx_hidden_TransferRxBytes = *b.TransferRxBytes
	}
	if b.TransferTxBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 14)
		x.xxx_hidden_TransferTxBytes = *b.TransferTxBytes
	}
	if b.PersistentKeepaliveSec != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 14)
		x.xxx_hidden_PersistentKeepaliveSec = *b.PersistentKeepaliveSec
	}
	if b.ConfirmedCarrierPayload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 14)
		x.xxx_hidden_ConfirmedCarrierPayload = *b.ConfirmedCarrierPayload
	}
	if b.PmtuSearching != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 14)
		x.xxx_hidden_PmtuSearching = *b.PmtuSearching
	}
	if b.DataReady != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 14)
		x.xxx_hidden_DataReady = *b.DataReady
	}
	if b.ControlPathState != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 14)
		x.xxx_hidden_ControlPathState = b.ControlPathState
	}
	if b.ControlPathError != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 14)
		x.xxx_hidden_ControlPathError = b.ControlPathError
	}
	if b.PresharedKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 14)
		x.xxx_hidden_PresharedKey = b.PresharedKey
	}
	if b.MetricsId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 14)
		x.xxx_hidden_MetricsId = b.MetricsId
	}
	return m0
}

type ShimCounters struct {
	state                                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TxCarriers                     uint64                 `protobuf:"varint,1,opt,name=tx_carriers,json=txCarriers"`
	xxx_hidden_TxPacketDrops                  uint64                 `protobuf:"varint,2,opt,name=tx_packet_drops,json=txPacketDrops"`
	xxx_hidden_TxRouteDrops                   uint64                 `protobuf:"varint,3,opt,name=tx_route_drops,json=txRouteDrops"`
	xxx_hidden_TxPeerMtuDrops                 uint64                 `protobuf:"varint,13,opt,name=tx_peer_mtu_drops,json=txPeerMtuDrops"`
	xxx_hidden_TxPtbSent                      uint64                 `protobuf:"varint,14,opt,name=tx_ptb_sent,json=txPtbSent"`
	xxx_hidden_ControlExploratoryEvictions    uint64                 `protobuf:"varint,15,opt,name=control_exploratory_evictions,json=controlExploratoryEvictions"`
	xxx_hidden_ControlCoalesces               uint64                 `protobuf:"varint,16,opt,name=control_coalesces,json=controlCoalesces"`
	xxx_hidden_ControlRateSuppressionEpisodes uint64                 `protobuf:"varint,17,opt,name=control_rate_suppression_episodes,json=controlRateSuppressionEpisodes"`
	xxx_hidden_ControlIngressRateLimited      uint64                 `protobuf:"varint,18,opt,name=control_ingress_rate_limited,json=controlIngressRateLimited"`
	xxx_hidden_RxDataCarriers                 uint64                 `protobuf:"varint,4,opt,name=rx_data_carriers,json=rxDataCarriers"`
	xxx_hidden_RxInnerDelivered               uint64                 `protobuf:"varint,5,opt,name=rx_inner_delivered,json=rxInnerDelivered"`
	xxx_hidden_RxPacketRejects                uint64                 `protobuf:"varint,6,opt,name=rx_packet_rejects,json=rxPacketRejects"`
	xxx_hidden_RxSourceSpoofDrops             uint64                 `protobuf:"varint,7,opt,name=rx_source_spoof_drops,json=rxSourceSpoofDrops"`
	xxx_hidden_RxNativeWriteDrops             uint64                 `protobuf:"varint,8,opt,name=rx_native_write_drops,json=rxNativeWriteDrops"`
	xxx_hidden_CarrierQueueOverflows          uint64                 `protobuf:"varint,9,opt,name=carrier_queue_overflows,json=carrierQueueOverflows"`
	xxx_hidden_PreconfirmDrops                uint64                 `protobuf:"varint,10,opt,name=preconfirm_drops,json=preconfirmDrops"`
	xxx_hidden_ReassemblyExpirations          uint64                 `protobuf:"varint,11,opt,name=reassembly_expirations,json=reassemblyExpirations"`
	xxx_hidden_UdpSocketDrops                 uint64                 `protobuf:"varint,12,opt,name=udp_socket_drops,json=udpSocketDrops"`
	xxx_hidden_ControlQueueDrops              uint64                 `protobuf:"varint,19,opt,name=control_queue_drops,json=controlQueueDrops"`
	xxx_hidden_ControlMaterializationDrops    uint64                 `protobuf:"varint,20,opt,name=control_materialization_drops,json=controlMaterializationDrops"`
	xxx_hidden_TxNativeFragmentDrops          uint64                 `protobuf:"varint,21,opt,name=tx_native_fragment_drops,json=txNativeFragmentDrops"`
	xxx_hidden_RxNativeFragmentDrops          uint64                 `protobuf:"varint,22,opt,name=rx_native_fragment_drops,json=rxNativeFragmentDrops"`
	XXX_raceDetectHookData                    protoimpl.RaceDetectHookData
	XXX_presence                              [1]uint32
	unknownFields                             protoimpl.UnknownFields
	sizeCache                                 protoimpl.SizeCache
}

func (x *ShimCounters) Reset() {
	*x = ShimCounters{}
	mi := &file_controlapi_v1_interface_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShimCounters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShimCounters) ProtoMessage() {}

func (x *ShimCounters) ProtoReflect() protoreflect.Message {
	mi := &file_controlapi_v1_interface_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ShimCounters) GetTxCarriers() uint64 {
	if x != nil {
		return x.xxx_hidden_TxCarriers
	}
	return 0
}

func (x *ShimCounters) GetTxPacketDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_TxPacketDrops
	}
	return 0
}

func (x *ShimCounters) GetTxRouteDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_TxRouteDrops
	}
	return 0
}

func (x *ShimCounters) GetTxPeerMtuDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_TxPeerMtuDrops
	}
	return 0
}

func (x *ShimCounters) GetTxPtbSent() uint64 {
	if x != nil {
		return x.xxx_hidden_TxPtbSent
	}
	return 0
}

func (x *ShimCounters) GetControlExploratoryEvictions() uint64 {
	if x != nil {
		return x.xxx_hidden_ControlExploratoryEvictions
	}
	return 0
}

func (x *ShimCounters) GetControlCoalesces() uint64 {
	if x != nil {
		return x.xxx_hidden_ControlCoalesces
	}
	return 0
}

func (x *ShimCounters) GetControlRateSuppressionEpisodes() uint64 {
	if x != nil {
		return x.xxx_hidden_ControlRateSuppressionEpisodes
	}
	return 0
}

func (x *ShimCounters) GetControlIngressRateLimited() uint64 {
	if x != nil {
		return x.xxx_hidden_ControlIngressRateLimited
	}
	return 0
}

func (x *ShimCounters) GetRxDataCarriers() uint64 {
	if x != nil {
		return x.xxx_hidden_RxDataCarriers
	}
	return 0
}

func (x *ShimCounters) GetRxInnerDelivered() uint64 {
	if x != nil {
		return x.xxx_hidden_RxInnerDelivered
	}
	return 0
}

func (x *ShimCounters) GetRxPacketRejects() uint64 {
	if x != nil {
		return x.xxx_hidden_RxPacketRejects
	}
	return 0
}

func (x *ShimCounters) GetRxSourceSpoofDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_RxSourceSpoofDrops
	}
	return 0
}

func (x *ShimCounters) GetRxNativeWriteDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_RxNativeWriteDrops
	}
	return 0
}

func (x *ShimCounters) GetCarrierQueueOverflows() uint64 {
	if x != nil {
		return x.xxx_hidden_CarrierQueueOverflows
	}
	return 0
}

func (x *ShimCounters) GetPreconfirmDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_PreconfirmDrops
	}
	return 0
}

func (x *ShimCounters) GetReassemblyExpirations() uint64 {
	if x != nil {
		return x.xxx_hidden_ReassemblyExpirations
	}
	return 0
}

func (x *ShimCounters) GetUdpSocketDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_UdpSocketDrops
	}
	return 0
}

func (x *ShimCounters) GetControlQueueDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_ControlQueueDrops
	}
	return 0
}

func (x *ShimCounters) GetControlMaterializationDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_ControlMaterializationDrops
	}
	return 0
}

func (x *ShimCounters) GetTxNativeFragmentDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_TxNativeFragmentDrops
	}
	return 0
}

func (x *ShimCounters) GetRxNativeFragmentDrops() uint64 {
	if x != nil {
		return x.xxx_hidden_RxNativeFragmentDrops
	}
	return 0
}

func (x *ShimCounters) SetTxCarriers(v uint64) {
	x.xxx_hidden_TxCarriers = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 22)
}

func (x *ShimCounters) SetTxPacketDrops(v uint64) {
	x.xxx_hidden_TxPacketDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 22)
}

func (x *ShimCounters) SetTxRouteDrops(v uint64) {
	x.xxx_hidden_TxRouteDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 22)
}

func (x *ShimCounters) SetTxPeerMtuDrops(v uint64) {
	x.xxx_hidden_TxPeerMtuDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 22)
}

func (x *ShimCounters) SetTxPtbSent(v uint64) {
	x.xxx_hidden_TxPtbSent = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 22)
}

func (x *ShimCounters) SetControlExploratoryEvictions(v uint64) {
	x.xxx_hidden_ControlExploratoryEvictions = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 22)
}

func (x *ShimCounters) SetControlCoalesces(v uint64) {
	x.xxx_hidden_ControlCoalesces = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 22)
}

func (x *ShimCounters) SetControlRateSuppressionEpisodes(v uint64) {
	x.xxx_hidden_ControlRateSuppressionEpisodes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 22)
}

func (x *ShimCounters) SetControlIngressRateLimited(v uint64) {
	x.xxx_hidden_ControlIngressRateLimited = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 22)
}

func (x *ShimCounters) SetRxDataCarriers(v uint64) {
	x.xxx_hidden_RxDataCarriers = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 22)
}

func (x *ShimCounters) SetRxInnerDelivered(v uint64) {
	x.xxx_hidden_RxInnerDelivered = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 22)
}

func (x *ShimCounters) SetRxPacketRejects(v uint64) {
	x.xxx_hidden_RxPacketRejects = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 22)
}

func (x *ShimCounters) SetRxSourceSpoofDrops(v uint64) {
	x.xxx_hidden_RxSourceSpoofDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 22)
}

func (x *ShimCounters) SetRxNativeWriteDrops(v uint64) {
	x.xxx_hidden_RxNativeWriteDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 22)
}

func (x *ShimCounters) SetCarrierQueueOverflows(v uint64) {
	x.xxx_hidden_CarrierQueueOverflows = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 14, 22)
}

func (x *ShimCounters) SetPreconfirmDrops(v uint64) {
	x.xxx_hidden_PreconfirmDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 15, 22)
}

func (x *ShimCounters) SetReassemblyExpirations(v uint64) {
	x.xxx_hidden_ReassemblyExpirations = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 16, 22)
}

func (x *ShimCounters) SetUdpSocketDrops(v uint64) {
	x.xxx_hidden_UdpSocketDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 17, 22)
}

func (x *ShimCounters) SetControlQueueDrops(v uint64) {
	x.xxx_hidden_ControlQueueDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 18, 22)
}

func (x *ShimCounters) SetControlMaterializationDrops(v uint64) {
	x.xxx_hidden_ControlMaterializationDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 19, 22)
}

func (x *ShimCounters) SetTxNativeFragmentDrops(v uint64) {
	x.xxx_hidden_TxNativeFragmentDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 20, 22)
}

func (x *ShimCounters) SetRxNativeFragmentDrops(v uint64) {
	x.xxx_hidden_RxNativeFragmentDrops = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 21, 22)
}

func (x *ShimCounters) HasTxCarriers() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ShimCounters) HasTxPacketDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ShimCounters) HasTxRouteDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ShimCounters) HasTxPeerMtuDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ShimCounters) HasTxPtbSent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ShimCounters) HasControlExploratoryEvictions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ShimCounters) HasControlCoalesces() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *ShimCounters) HasControlRateSuppressionEpisodes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *ShimCounters) HasControlIngressRateLimited() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *ShimCounters) HasRxDataCarriers() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *ShimCounters) HasRxInnerDelivered() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *ShimCounters) HasRxPacketRejects() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *ShimCounters) HasRxSourceSpoofDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *ShimCounters) HasRxNativeWriteDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *ShimCounters) HasCarrierQueueOverflows() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 14)
}

func (x *ShimCounters) HasPreconfirmDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 15)
}

func (x *ShimCounters) HasReassemblyExpirations() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 16)
}

func (x *ShimCounters) HasUdpSocketDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 17)
}

func (x *ShimCounters) HasControlQueueDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 18)
}

func (x *ShimCounters) HasControlMaterializationDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 19)
}

func (x *ShimCounters) HasTxNativeFragmentDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 20)
}

func (x *ShimCounters) HasRxNativeFragmentDrops() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 21)
}

func (x *ShimCounters) ClearTxCarriers() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TxCarriers = 0
}

func (x *ShimCounters) ClearTxPacketDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TxPacketDrops = 0
}

func (x *ShimCounters) ClearTxRouteDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_TxRouteDrops = 0
}

func (x *ShimCounters) ClearTxPeerMtuDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_TxPeerMtuDrops = 0
}

func (x *ShimCounters) ClearTxPtbSent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_TxPtbSent = 0
}

func (x *ShimCounters) ClearControlExploratoryEvictions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_ControlExploratoryEvictions = 0
}

func (x *ShimCounters) ClearControlCoalesces() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_ControlCoalesces = 0
}

func (x *ShimCounters) ClearControlRateSuppressionEpisodes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_ControlRateSuppressionEpisodes = 0
}

func (x *ShimCounters) ClearControlIngressRateLimited() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_ControlIngressRateLimited = 0
}

func (x *ShimCounters) ClearRxDataCarriers() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_RxDataCarriers = 0
}

func (x *ShimCounters) ClearRxInnerDelivered() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_RxInnerDelivered = 0
}

func (x *ShimCounters) ClearRxPacketRejects() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_RxPacketRejects = 0
}

func (x *ShimCounters) ClearRxSourceSpoofDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_RxSourceSpoofDrops = 0
}

func (x *ShimCounters) ClearRxNativeWriteDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_RxNativeWriteDrops = 0
}

func (x *ShimCounters) ClearCarrierQueueOverflows() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 14)
	x.xxx_hidden_CarrierQueueOverflows = 0
}

func (x *ShimCounters) ClearPreconfirmDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 15)
	x.xxx_hidden_PreconfirmDrops = 0
}

func (x *ShimCounters) ClearReassemblyExpirations() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 16)
	x.xxx_hidden_ReassemblyExpirations = 0
}

func (x *ShimCounters) ClearUdpSocketDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 17)
	x.xxx_hidden_UdpSocketDrops = 0
}

func (x *ShimCounters) ClearControlQueueDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 18)
	x.xxx_hidden_ControlQueueDrops = 0
}

func (x *ShimCounters) ClearControlMaterializationDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 19)
	x.xxx_hidden_ControlMaterializationDrops = 0
}

func (x *ShimCounters) ClearTxNativeFragmentDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 20)
	x.xxx_hidden_TxNativeFragmentDrops = 0
}

func (x *ShimCounters) ClearRxNativeFragmentDrops() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 21)
	x.xxx_hidden_RxNativeFragmentDrops = 0
}

type ShimCounters_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TxCarriers                     *uint64
	TxPacketDrops                  *uint64
	TxRouteDrops                   *uint64
	TxPeerMtuDrops                 *uint64
	TxPtbSent                      *uint64
	ControlExploratoryEvictions    *uint64
	ControlCoalesces               *uint64
	ControlRateSuppressionEpisodes *uint64
	ControlIngressRateLimited      *uint64
	RxDataCarriers                 *uint64
	RxInnerDelivered               *uint64
	RxPacketRejects                *uint64
	RxSourceSpoofDrops             *uint64
	RxNativeWriteDrops             *uint64
	CarrierQueueOverflows          *uint64
	PreconfirmDrops                *uint64
	ReassemblyExpirations          *uint64
	UdpSocketDrops                 *uint64
	ControlQueueDrops              *uint64
	ControlMaterializationDrops    *uint64
	TxNativeFragmentDrops          *uint64
	RxNativeFragmentDrops          *uint64
}

func (b0 ShimCounters_builder) Build() *ShimCounters {
	m0 := &ShimCounters{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TxCarriers != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 22)
		x.xxx_hidden_TxCarriers = *b.TxCarriers
	}
	if b.TxPacketDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 22)
		x.xxx_hidden_TxPacketDrops = *b.TxPacketDrops
	}
	if b.TxRouteDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 22)
		x.xxx_hidden_TxRouteDrops = *b.TxRouteDrops
	}
	if b.TxPeerMtuDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 22)
		x.xxx_hidden_TxPeerMtuDrops = *b.TxPeerMtuDrops
	}
	if b.TxPtbSent != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 22)
		x.xxx_hidden_TxPtbSent = *b.TxPtbSent
	}
	if b.ControlExploratoryEvictions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 22)
		x.xxx_hidden_ControlExploratoryEvictions = *b.ControlExploratoryEvictions
	}
	if b.ControlCoalesces != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 22)
		x.xxx_hidden_ControlCoalesces = *b.ControlCoalesces
	}
	if b.ControlRateSuppressionEpisodes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 22)
		x.xxx_hidden_ControlRateSuppressionEpisodes = *b.ControlRateSuppressionEpisodes
	}
	if b.ControlIngressRateLimited != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 22)
		x.xxx_hidden_ControlIngressRateLimited = *b.ControlIngressRateLimited
	}
	if b.RxDataCarriers != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 22)
		x.xxx_hidden_RxDataCarriers = *b.RxDataCarriers
	}
	if b.RxInnerDelivered != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 22)
		x.xxx_hidden_RxInnerDelivered = *b.RxInnerDelivered
	}
	if b.RxPacketRejects != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 22)
		x.xxx_hidden_RxPacketRejects = *b.RxPacketRejects
	}
	if b.RxSourceSpoofDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 22)
		x.xxx_hidden_RxSourceSpoofDrops = *b.RxSourceSpoofDrops
	}
	if b.RxNativeWriteDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 22)
		x.xxx_hidden_RxNativeWriteDrops = *b.RxNativeWriteDrops
	}
	if b.CarrierQueueOverflows != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 14, 22)
		x.xxx_hidden_CarrierQueueOverflows = *b.CarrierQueueOverflows
	}
	if b.PreconfirmDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 15, 22)
		x.xxx_hidden_PreconfirmDrops = *b.PreconfirmDrops
	}
	if b.ReassemblyExpirations != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 16, 22)
		x.xxx_hidden_ReassemblyExpirations = *b.ReassemblyExpirations
	}
	if b.UdpSocketDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 17, 22)
		x.xxx_hidden_UdpSocketDrops = *b.UdpSocketDrops
	}
	if b.ControlQueueDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 18, 22)
		x.xxx_hidden_ControlQueueDrops = *b.ControlQueueDrops
	}
	if b.ControlMaterializationDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 19, 22)
		x.xxx_hidden_ControlMaterializationDrops = *b.ControlMaterializationDrops
	}
	if b.TxNativeFragmentDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 20, 22)
		x.xxx_hidden_TxNativeFragmentDrops = *b.TxNativeFragmentDrops
	}
	if b.RxNativeFragmentDrops != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 21, 22)
		x.xxx_hidden_RxNativeFragmentDrops = *b.RxNativeFragmentDrops
	}
	return m0
}

var File_controlapi_v1_interface_proto protoreflect.FileDescriptor

const file_controlapi_v1_interface_proto_rawDesc = "" +
	"\n" +
	"\x1dcontrolapi/v1/interface.proto\x12\x11wgf.controlapi.v1\x1a\x1acontrolapi/v1/common.proto\"\x99\x05\n" +
	"\rInterfaceSpec\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12\x1f\n" +
	"\vprivate_key\x18\x02 \x01(\fR\n" +
	"privateKey\x12\x1f\n" +
	"\vlisten_port\x18\x03 \x01(\rR\n" +
	"listenPort\x12\x10\n" +
	"\x03mtu\x18\x04 \x01(\rR\x03mtu\x12#\n" +
	"\rmtu_discovery\x18\x05 \x01(\tR\fmtuDiscovery\x12.\n" +
	"\x13min_carrier_payload\x18\x06 \x01(\rR\x11minCarrierPayload\x12.\n" +
	"\x13max_carrier_payload\x18\a \x01(\rR\x11maxCarrierPayload\x12)\n" +
	"\x10reassembly_slots\x18\b \x01(\rR\x0freassemblySlots\x122\n" +
	"\x15peer_reassembly_slots\x18\t \x01(\rR\x13peerReassemblySlots\x124\n" +
	"\x16reassembly_lifetime_ms\x18\n" +
	" \x01(\rR\x14reassemblyLifetimeMs\x12\x18\n" +
	"\areorder\x18\v \x01(\bR\areorder\x12/\n" +
	"\x14reorder_max_delay_ms\x18\f \x01(\rR\x11reorderMaxDelayMs\x12\x18\n" +
	"\aworkers\x18\r \x01(\rR\aworkers\x12\x1d\n" +
	"\n" +
	"tun_queues\x18\x0e \x01(\rR\ttunQueues\x12#\n" +
	"\rsocket_buffer\x18\x0f \x01(\rR\fsocketBuffer\x12\x17\n" +
	"\afw_mark\x18\x10 \x01(\rR\x06fwMark\x121\n" +
	"\x05peers\x18\x11 \x03(\v2\x1b.wgf.controlapi.v1.PeerSpecR\x05peers\"\xbd\x02\n" +
	"\bPeerSpec\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x03 \x03(\tR\n" +
	"allowedIps\x128\n" +
	"\x18persistent_keepalive_sec\x18\x04 \x01(\rR\x16persistentKeepaliveSec\x12#\n" +
	"\rpreshared_key\x18\x05 \x01(\fR\fpresharedKey\x12W\n" +
	"\x14preshared_key_action\x18\x06 \x01(\x0e2%.wgf.controlapi.v1.PresharedKeyActionR\x12presharedKeyAction\x12\x1d\n" +
	"\n" +
	"metrics_id\x18\a \x01(\tR\tmetricsId\"\x80\x04\n" +
	"\x0fInterfaceStatus\x121\n" +
	"\x03ref\x18\x01 \x01(\v2\x1f.wgf.controlapi.v1.InterfaceRefR\x03ref\x12C\n" +
	"\tlifecycle\x18\x02 \x01(\x0e2%.wgf.controlapi.v1.InterfaceLifecycleR\tlifecycle\x12'\n" +
	"\x0flifecycle_error\x18\x03 \x01(\tR\x0elifecycleError\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vlisten_port\x18\x05 \x01(\rR\n" +
	"listenPort\x12\x10\n" +
	"\x03mtu\x18\x06 \x01(\rR\x03mtu\x12;\n" +
	"\bcounters\x18\a \x01(\v2\x1f.wgf.controlapi.v1.ShimCountersR\bcounters\x123\n" +
	"\x05peers\x18\b \x03(\v2\x1d.wgf.controlapi.v1.PeerStatusR\x05peers\x12\x1e\n" +
	"\n" +
	"generation\x18\t \x01(\x04R\n" +
	"generation\x124\n" +
	"\x04spec\x18\n" +
	" \x01(\v2 .wgf.controlapi.v1.InterfaceSpecR\x04spec\x122\n" +
	"\x15native_interface_name\x18\v \x01(\tR\x13nativeInterfaceName\"\xcc\x04\n" +
	"\n" +
	"PeerStatus\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x03 \x03(\tR\n" +
	"allowedIps\x12.\n" +
	"\x13last_handshake_unix\x18\x04 \x01(\x03R\x11lastHandshakeUnix\x12*\n" +
	"\x11transfer_rx_bytes\x18\x05 \x01(\x04R\x0ftransferRxBytes\x12*\n" +
	"\x11transfer_tx_bytes\x18\x06 \x01(\x04R\x0ftransferTxBytes\x128\n" +
	"\x18persistent_keepalive_sec\x18\a \x01(\rR\x16persistentKeepaliveSec\x12:\n" +
	"\x19confirmed_carrier_payload\x18\b \x01(\rR\x17confirmedCarrierPayload\x12%\n" +
	"\x0epmtu_searching\x18\t \x01(\bR\rpmtuSearching\x12\x1d\n" +
	"\n" +
	"data_ready\x18\n" +
	" \x01(\bR\tdataReady\x12,\n" +
	"\x12control_path_state\x18\v \x01(\tR\x10controlPathState\x12,\n" +
	"\x12control_path_error\x18\f \x01(\tR\x10controlPathError\x12#\n" +
	"\rpreshared_key\x18\r \x01(\fR\fpresharedKey\x12\x1d\n" +
	"\n" +
	"metrics_id\x18\x0e \x01(\tR\tmetricsId\"\xd9\b\n" +
	"\fShimCounters\x12\x1f\n" +
	"\vtx_carriers\x18\x01 \x01(\x04R\n" +
	"txCarriers\x12&\n" +
	"\x0ftx_packet_drops\x18\x02 \x01(\x04R\rtxPacketDrops\x12$\n" +
	"\x0etx_route_drops\x18\x03 \x01(\x04R\ftxRouteDrops\x12)\n" +
	"\x11tx_peer_mtu_drops\x18\r \x01(\x04R\x0etxPeerMtuDrops\x12\x1e\n" +
	"\vtx_ptb_sent\x18\x0e \x01(\x04R\ttxPtbSent\x12B\n" +
	"\x1dcontrol_exploratory_evictions\x18\x0f \x01(\x04R\x1bcontrolExploratoryEvictions\x12+\n" +
	"\x11control_coalesces\x18\x10 \x01(\x04R\x10controlCoalesces\x12I\n" +
	"!control_rate_suppression_episodes\x18\x11 \x01(\x04R\x1econtrolRateSuppressionEpisodes\x12?\n" +
	"\x1ccontrol_ingress_rate_limited\x18\x12 \x01(\x04R\x19controlIngressRateLimited\x12(\n" +
	"\x10rx_data_carriers\x18\x04 \x01(\x04R\x0erxDataCarriers\x12,\n" +
	"\x12rx_inner_delivered\x18\x05 \x01(\x04R\x10rxInnerDelivered\x12*\n" +
	"\x11rx_packet_rejects\x18\x06 \x01(\x04R\x0frxPacketRejects\x121\n" +
	"\x15rx_source_spoof_drops\x18\a \x01(\x04R\x12rxSourceSpoofDrops\x121\n" +
	"\x15rx_native_write_drops\x18\b \x01(\x04R\x12rxNativeWriteDrops\x126\n" +
	"\x17carrier_queue_overflows\x18\t \x01(\x04R\x15carrierQueueOverflows\x12)\n" +
	"\x10preconfirm_drops\x18\n" +
	" \x01(\x04R\x0fpreconfirmDrops\x125\n" +
	"\x16reassembly_expirations\x18\v \x01(\x04R\x15reassemblyExpirations\x12(\n" +
	"\x10udp_socket_drops\x18\f \x01(\x04R\x0eudpSocketDrops\x12.\n" +
	"\x13control_queue_drops\x18\x13 \x01(\x04R\x11controlQueueDrops\x12B\n" +
	"\x1dcontrol_materialization_drops\x18\x14 \x01(\x04R\x1bcontrolMaterializationDrops\x127\n" +
	"\x18tx_native_fragment_drops\x18\x15 \x01(\x04R\x15txNativeFragmentDrops\x127\n" +
	"\x18rx_native_fragment_drops\x18\x16 \x01(\x04R\x15rxNativeFragmentDrops*6\n" +
	"\x12PresharedKeyAction\x12\f\n" +
	"\bPRESERVE\x10\x00\x12\a\n" +
	"\x03SET\x10\x01\x12\t\n" +
	"\x05CLEAR\x10\x02BAZ?github.com/kurochan/wg-frag-go/proto/controlapi/v1;controlapiv1b\beditionsp\xe9\a"

var file_controlapi_v1_interface_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controlapi_v1_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_controlapi_v1_interface_proto_goTypes = []any{
	(PresharedKeyAction)(0), // 0: wgf.controlapi.v1.PresharedKeyAction
	(*InterfaceSpec)(nil),   // 1: wgf.controlapi.v1.InterfaceSpec
	(*PeerSpec)(nil),        // 2: wgf.controlapi.v1.PeerSpec
	(*InterfaceStatus)(nil), // 3: wgf.controlapi.v1.InterfaceStatus
	(*PeerStatus)(nil),      // 4: wgf.controlapi.v1.PeerStatus
	(*ShimCounters)(nil),    // 5: wgf.controlapi.v1.ShimCounters
	(*InterfaceRef)(nil),    // 6: wgf.controlapi.v1.InterfaceRef
	(InterfaceLifecycle)(0), // 7: wgf.controlapi.v1.InterfaceLifecycle
}
var file_controlapi_v1_interface_proto_depIdxs = []int32{
	2, // 0: wgf.controlapi.v1.InterfaceSpec.peers:type_name -> wgf.controlapi.v1.PeerSpec
	0, // 1: wgf.controlapi.v1.PeerSpec.preshared_key_action:type_name -> wgf.controlapi.v1.PresharedKeyAction
	6, // 2: wgf.controlapi.v1.InterfaceStatus.ref:type_name -> wgf.controlapi.v1.InterfaceRef
	7, // 3: wgf.controlapi.v1.InterfaceStatus.lifecycle:type_name -> wgf.controlapi.v1.InterfaceLifecycle
	5, // 4: wgf.controlapi.v1.InterfaceStatus.counters:type_name -> wgf.controlapi.v1.ShimCounters
	4, // 5: wgf.controlapi.v1.InterfaceStatus.peers:type_name -> wgf.controlapi.v1.PeerStatus
	1, // 6: wgf.controlapi.v1.InterfaceStatus.spec:type_name -> wgf.controlapi.v1.InterfaceSpec
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_controlapi_v1_interface_proto_init() }
func file_controlapi_v1_interface_proto_init() {
	if File_controlapi_v1_interface_proto != nil {
		return
	}
	file_controlapi_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlapi_v1_interface_proto_rawDesc), len(file_controlapi_v1_interface_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controlapi_v1_interface_proto_goTypes,
		DependencyIndexes: file_controlapi_v1_interface_proto_depIdxs,
		EnumInfos:         file_controlapi_v1_interface_proto_enumTypes,
		MessageInfos:      file_controlapi_v1_interface_proto_msgTypes,
	}.Build()
	File_controlapi_v1_interface_proto = out.File
	file_controlapi_v1_interface_proto_goTypes = nil
	file_controlapi_v1_interface_proto_depIdxs = nil
}
